### ISSUE TITLE
Make a safe plan

### ISSUE THREAD

**Issue by Zerek-Cheng** [KaiKikuchi/QuickShop#100]
we can add a sign to the floater（shower）

if the player or a block get the floater（shower）

we can take that item（shower） immediately

**Comment by KaiKikuchi** [comment]
Sorry I don't understand. Can you post a screenshot?

**Comment by Zerek-Cheng** [comment]
Some players will use BUG to get the floating objects
I think we need to make a mark on the float
Remove this item from the backpack when we find the mark

**Comment by KaiKikuchi** [comment]
I am deeply sorry but I really can't understand how to use the bug you say.

Can you upload screenshots or a video with the bug please? I will fix it if you can do that.
