### ISSUE TITLE
Spigot Page and Tutorial neglects to mention that you have to sneak to make a chest a shop

### ISSUE THREAD

**Issue by heartsemma** [KaiKikuchi/QuickShop#106]
Title.

I was very confused on how players were supposed to actually break chests until I went into the code and saw that you checked for shift-clicks instead of just regular left-clicks.

**Comment by KaiKikuchi** [comment]
The shift-click is disabled by default:
https://github.com/KaiKikuchi/QuickShop/blob/master/src/main/resources/config.yml#L68-L70

Also I've tested wihtout the shift-click on all versions up to Spigot 1.11.2, and it works just fine for me. I think you're using a broken Spigot build. Please update to the latest Spigot, or report the exact version you're using.

Btw, I'll add a note to the page.
