### ISSUE TITLE
World Support?

### ISSUE THREAD

**Issue by Bandi42Plays** [KaiKikuchi/QuickShop#107]
Having an issue where players in MobArena can place shops on chests making them unusable to players. It also allows them to give items to themselves as different classes. A simple fix would be Multi-World support.

**Comment by KaiKikuchi** [comment]
Hello. Sorry for the late reply. You can use your permission plugin (pex) or area plugin (worldguard) to deny permission to create shop chests in certain areas/worlds.

If you're using WorldGuard, this may help you: https://github.com/KaiKikuchi/QuickShopWG
