### ISSUE TITLE
Item frames not being created

### ISSUE THREAD

**Issue by Eufranio** [KaiKikuchi/QuickShop#109]
After creating a shop with QuickShop, the item-frame will not appear. Instead, it will print an error in the console, with no stacktrace:

```
java.lang.NullPointerException: playerId
```

Using QuickShop 0.9.29 on a Thermos 1.7.10 B58 server.

**Comment by KaiKikuchi** [comment]
Afaik, the "item frames" never worked and I will probably remove it so just signs and the "display item above the chest" will be available.

**Comment by Eufranio** [comment]
Why? They are nice in modded servers where the fake items cause issues with mods and still showing the item being sold.

**Comment by KaiKikuchi** [comment]
Yes. I am thinking about fixing that by providing players a way to actually see what is the item being sold with a actual "chest" interface. Of course, players can't get that item.

**Comment by Eufranio** [comment]
Showing it on an item frame would be better I think, GUIs would be far from the original ideia of the plugin (chest shops)

**Comment by KaiKikuchi** [comment]
Items inside item frames are prone to being duped. Some server even ban them. And I can't assure the item frame won't cause duped items. I'm sorry.

**Comment by Eufranio** [comment]
>item frames
>dupes
wtf?

**Comment by Eufranio** [comment]
You really can't assure, that's why there is a **config option**, but implementing this or not is up to you.

**Comment by KaiKikuchi** [comment]
You may not know that this plugin is very ancient, and a lot of things were already broken and they got removed by previous developers (I just inherited the plugin to make it compatible with latest versions at least for the main features). You may not be aware of dupes involving item frames and that's okay.

Still, it's not like I have to write a magic line and everything start working... developing stuff requires A LOT of time, and I am contributing to this project for free. As I have a lot more important and requested things to do, I cannot work on it. You or someone else can definitely contribute to the project by implementing that feature, but I will not do it.
