### ISSUE TITLE
[Suggestion] Adding minimal/maximal prices for an item

### ISSUE THREAD

**Issue by TNTUP** [KaiKikuchi/QuickShop#11]
Hi, it would be nice if its possible, to add an option so we can either set a minimum price on a item or set a maximum price to avoid abuse (like selling diamonds to 0.5 instead of minium price set on the server)

**Comment by KaiKikuchi** [comment]
Hello, thank you for your suggestion! This can be easily added into QuickShop, or as a QuickShop extension. Unfortunately I don't have time to do this atm. If someone else wants to develop this feature, let me know. Otherwise, I'll do it when possible!

**Comment by TNTUP** [comment]
Do it when you have free time, this is not urgent, I wish if its in QS not an extension (I try to keep a lower plugin count) atm i have 80 xDD

**Comment by KaiKikuchi** [comment]
I'm for modularity. You may need this feature, but someone else may not and with this feature implemented directly on QS forces to load in memory something that it's not needed.
The plugins amount isn't important at all. A QuickShop extension that checks the prices, if it's coded properly, doesn't affect the performances at all. The overhead is very little and insignificant.
Modularity increase extension possibilities and makes development easier.
Moreover, anyone can make an extension by themselves.

**Comment by KaiKikuchi** [comment]
Added on QuickShop v.0.9.10
