### ISSUE TITLE
clarification and requests

### ISSUE THREAD

**Issue by smmmadden** [KaiKikuchi/QuickShop#114]
Hi @KaiKikuchi I've started the switch to using this plugin over the defunct and unsupported ChestShop.  I've posted on Spigot the below and seems you may not have seen it there, so posting here.  Hopefully, this is something that can be supported.  Thanks!

**April 10, 2017:** I've been playing around with this and just now converting my servers. One thing I read is that the config.yml can limit the number of shops a player can create when limits: Use: true is set does it only then set the default to 10? If a player has quickshop.vip: 20 then players with quickshop.vip can make 20 shops. 
1. Is 1 single or double chest considered one Shop?

2. Is it required to enable limits in order to enable the permission of quickshop.vip? I ask as I'd like to add the setting for each permissions group, but set the default based on which group you're in. For example, if you log in as a new user, you can create 1 shop (chest). But if you are a user with a higher ranking or different group, that group of users can have a higher number of shops/chests (say 50). Then if you're an admin and playing or setting up a server shop, there would be no limit (high value of say 1000).

3. By default the sign is placed on the front of the chest leaving no place to put the item frame with a picture of what's inside. I didn't see any way in the config.yml to place the sign on top. Is there a way to do this so we can have the sign on top that users click, but front of chest with the item frame and item image on it?

4. The name of the shop defaults to QuickShop for every player, is this customizable to have the players name on it instead so we can tell one players shop from another? The sign itself cannot be edited even with EditableSign plugin. That would allow players to change the first row to their choosing.

Thanks!
Edit: 4/28/2017 - no response? :-(

**Comment by KaiKikuchi** [comment]
Hello. I do not have time to check if someone sent a message on all the platforms this plugin is hosted on. As I specified on all posts, Github is the only way to get support from me, so if you read that you would have known that already.

https://github.com/KaiKikuchi/QuickShop/blob/master/src/main/resources/config.yml#L30-L40

The default is 10, so unless you change that anyone that does not have any permission rank will have just the default amount.

> Is 1 single or double chest considered one Shop?

Yes. Unless you attach 2 signs on a double chest, in this case it would be two shops. Every sign on the chest is one shop.


> Is it required to enable limits in order to enable the permission of quickshop.vip?

Yes. Be sure to set the default to the lowest rank (the one for new players I guess), then make a new rank for each higher rank with the desired shops amount.


> By default the sign is placed on the front of the chest leaving no place to put the item frame with a picture of what's inside. [..] Is there a way to do this so we can have the sign on top that users click, but front of chest with the item frame and item image on it?

I'm afraid that can't be possible.


> The name of the shop defaults to QuickShop for every player, is this customizable to have the players name on it instead so we can tell one players shop from another?

I'm sorry but this is not possible with the current version of QuickShop. Maybe this will be a thing on newer versions. No ETA.

**Comment by smmmadden** [comment]
Sorry, I saw that and realized this is where I should have posted.  It's hard for me to have to check 80+ plugins on every discussion board too for answers, so I totally get that. :-)

Thanks for the responses, this helps a lot so I can move forward.  I can live without the frame, though I thought that's what this setting meant to do?  Is there a different purpose or usage of "frame".  I think of it as an item_frame, but probably wrong there.
    #Should we place item frames on chests?
    frame-items: true
Since you know it is a quickshop shop, having usage of the first row for the owner would be ideal.  Here is what I'm referring to so you have a visual of yours and the previous plugin named above. :-)
![image](https://cloud.githubusercontent.com/assets/10309346/25834002/1beff4b8-3443-11e7-9979-97b41ed45287.png)
Thanks again for the quick reply.

**Comment by KaiKikuchi** [comment]
I am not the original developer of this plugin. I took the project from other developers that abandoned this project. I made a lot of fixes to avoid duping and to improve compatibility with newer bukkit versions.

About the "[QuickShop]" line, it is not really necessary. Removing it should be possible with some code modification. Although I think it is possible to modify it, I am currently forced to work for paid/private plugins only due to irl circumstances and because people contact me for that. Even if I love open source and I really want to support it, I have to pay bills!

So there's always room for improvements, but I am lacking time. If you're a developer or you hire a developer he can contribute to the project or just make it a personal thing for your server only. QuickShop is licensed GPL v3 and allows that.

**Comment by smmmadden** [comment]
I'm more than happy to donate to the work you're doing on this, that's not a problem.  I start with converstaions, analyse results and determine if a) this is a future direction for my players and b) if donation helps achieve that, I'm all for supporting and anyone doing just that :-)

**Comment by smmmadden** [comment]
Also, looking to be able to sell in larger quantities than just one item at a time.  Is there a config setting or command that allows me to specify the number of blocks to sell for the one price?  Like in the image above right, players can buy 64 Cobblestone Stairs for $75.  Each chest could be different though, so it would need to be flexible enough to set the quantity and price for each chest.  Same goes for buying, the chest owner could specify he/she will buy back one/many blocks for xxx.xx price which could be the same or lower (typical).

**Comment by KaiKikuchi** [comment]
Sorry, I think that having the quantity adds more complexity to the plugin so I stay with the original developers decision to limit it to 1 item. Instead of selling 64x cobble stairs for $75, you can sell 1 for $1.17 each. Whenever a player wants to buy a stack of cobble stairs, they can click on the chest and write 64, or the precise amount they need, so they do not have to buy an entire stack even if they do not need part of it.

**Comment by smmmadden** [comment]
Right, that does make sense and makes it easy to sell any quantity from the chest.  Thanks!

**Comment by smmmadden** [comment]
closing this topic and will open specific issues as needed.
