### ISSUE TITLE
Breaking active sign, unable to replace sign

### ISSUE THREAD

**Issue by smmmadden** [KaiKikuchi/QuickShop#116]
During the conversion of my signs from ChestShop to QuickShop, I broke the original sign, faced the chest and left shift/left clicked the chest with the item to create my shop for that item.  That worked fine.  I had broken the sign but was still allowed to buy from the shop even though there was no visible indication of a shop.  I tried to re-create the sign, but no command allows the recreation of a missing sign.  Nor could I remove the shop without breaking the chest to start all over.  
Steps: Create a shop, break the sign, try to put another sign on the chest

**Comment by KaiKikuchi** [comment]
You just have to put a new sign on the chest, and then click on the chest.

**Comment by smmmadden** [comment]
Thanks, a blank sign placed and re-click worked perfectly. :-)
