### ISSUE TITLE
changing shop from XXX to YYY

### ISSUE THREAD

**Issue by smmmadden** [KaiKikuchi/QuickShop#119]
Is there a simple way to change a shop that was accidentally created as XXX when it should be YYY?  If I break the sign, it doesn't de-register that shop, so clicking on it with a different item doesn't get registered as a new shop.  Possibly need a /qs or /shop remove so it removes the current shop pointing at?  Thanks!

**Comment by KaiKikuchi** [comment]
Do you mean, the owner is wrong? You can easily edit it with a SQLite editor if you're using SQLite as database.

**Comment by smmmadden** [comment]
no, the owner is fine (but it could be either way).  It's what the shop sells is the issue.  Given that every interaction to set the price after creating the chest results in the user pressing T (or other key) to get to the chat window, often times I find myself typing the number before doing the T for chat and then what I created for the shop is incorrect.  Doesn't necessarily matter for the how, what I'm not finding is any way to a) remove a shop or b) edit the shop and change the contents.  So XXX could be DIRT and YYY could be COBBLESTONE.  Once the shop is created for DIRT, breaking the sign doesn't unregister that shop.  The only option is breaking the chest which isn't an option.   So /shop change (to change the block type of the shop) and /shop remove (delete the shop so it can be recreated by another block).

Does that help?

**Comment by KaiKikuchi** [comment]
> often times I find myself typing the number before doing the T for chat and then what I created for the shop is incorrect

Sorry there isn't really anything that I can do for that. There isn't any way for a server to automatically prompt the user chat. Players must write in chat the amount or the price when asked to.

> a) remove a shop

You can either break the chest, or use the `/qs remove` command while looking at the shop chest. The `quickshop.delete` permission is required.

> b) edit the shop and change the contents.

First use the `/qs remove` command, then make a new shop chest.

> The only option is breaking the chest which isn't an option.

Then `/qs remove` is your only option.
