### ISSUE TITLE
Blacklist does not work with meta data.

### ISSUE THREAD

**Issue by ghost** [KaiKikuchi/QuickShop#12]
When trying to add in modded items to the blacklist and reload the plugin, QuickShop stops working until the modded item is removed from the blacklist. To make sure it wasn't an error on my part, I tired the following:
- (t/T)hermal(f/F)oundation_(m/M)aterial:70
- (t/T)hermal(f/F)oundation_(m/M)aterial
- (t/T)hermal(f/F)oundation:(m/M)aterial:70
- (t/T)hermal(f/F)oundation:(m/M)aterial

And even the item ID that Forge assigns it when the world is first generated. The full list of items I'm trying to blacklist are in the pastebin below:

http://pastebin.com/ehd64Sgq

After I remove the items commented out, QuickShop works like it should.

Thank you for reading!

EDIT: So it turns out, the issue wasn't the modded items, it was the meta data of the modded items. Not sure if this would be a quick fix, or something that would require a little time to figure out.

**Comment by KaiKikuchi** [comment]
You can't add the metadata to the blacklisted name. Metadata is totally ignored. This means that if you add "BIGREACTORS_BRINGOT" to the blacklist, any metadata for that item id is blacklisted.
