### ISSUE TITLE
Acacia & Dark Oak Log Names missing

### ISSUE THREAD

**Issue by smmmadden** [KaiKikuchi/QuickShop#120]
**Acacia Log**
![image](https://cloud.githubusercontent.com/assets/10309346/26030606/aebb9244-3825-11e7-93e9-96a80c78d3ab.png)
**Chat Window not showing the Log Name**
![image](https://cloud.githubusercontent.com/assets/10309346/26030620/f7c407be-3825-11e7-83d6-8a73d25ae000.png)

**Dark Oak Log**
![image](https://cloud.githubusercontent.com/assets/10309346/26030607/b86d73ca-3825-11e7-99d1-b5b7b95acda0.png)
**Chat Window not showing the Log Name**
![image](https://cloud.githubusercontent.com/assets/10309346/26030613/d4a36f90-3825-11e7-8430-6b881f60a6af.png)

Same is true for the Planks for these two blocks. They appear as "Wood", but should be AcaciaPlanks and DarkOakPlanks

Spruce Logs and Planks is showing as "Pine" - there is no Pine in Minecraft (as of 1.11.2)
![image](https://cloud.githubusercontent.com/assets/10309346/26033939/bb57e77a-3882-11e7-88cc-948fc741d118.png)

![image](https://cloud.githubusercontent.com/assets/10309346/26033944/c47508a6-3882-11e7-9a87-5c936aba45b5.png)
![image](https://cloud.githubusercontent.com/assets/10309346/26033981/6e8ba69c-3883-11e7-8c9f-9db005cac152.png)

**Comment by KaiKikuchi** [comment]
Check my reply here: https://github.com/KaiKikuchi/QuickShop/issues/121
