### ISSUE TITLE
Stone:1 shop should say "Granite"

### ISSUE THREAD

**Issue by smmmadden** [KaiKikuchi/QuickShop#121]
![image](https://cloud.githubusercontent.com/assets/10309346/26030779/7385d512-382b-11e7-8a21-623dfbf0abe9.png)
![image](https://cloud.githubusercontent.com/assets/10309346/26030780/79e03510-382b-11e7-9eba-abb754f5c352.png)

Stone:2 should say "Polished Granite" or "Smooth Granite"
![image](https://cloud.githubusercontent.com/assets/10309346/26030783/ae3c83ae-382b-11e7-9c40-2c69bf68b8b1.png)

**Comment by smmmadden** [comment]
Stone:3 should also be "Diorite"
![image](https://cloud.githubusercontent.com/assets/10309346/26030791/0c14d1de-382c-11e7-8ccd-6eb2610a06e0.png)
Stone:4 should also be "Polished Diorite" or "Smooth Diorite"
![image](https://cloud.githubusercontent.com/assets/10309346/26030795/31323c72-382c-11e7-83c3-02d8d8eb50a8.png)

**Comment by smmmadden** [comment]
Stone:5 should read as "Andesite"
![image](https://cloud.githubusercontent.com/assets/10309346/26030823/e95a9240-382c-11e7-8545-b20689fcba1d.png)
Stone:6 should read as "Polished Andesite" or "Smooth Andesite"
![image](https://cloud.githubusercontent.com/assets/10309346/26030831/1ea278b4-382d-11e7-8c7a-aff970c1111c.png)

**Comment by smmmadden** [comment]
![image](https://cloud.githubusercontent.com/assets/10309346/26030942/a6d901aa-3830-11e7-9998-3dc2e405a538.png)

**Comment by smmmadden** [comment]
should you be able to make the changes I've reported, do let me know how I can donate $ to your time.  I gladly support those who supports the server owners. :-)

**Comment by KaiKikuchi** [comment]
Welp.

Unfortunately Bukkit API doesn't provide a good way to show item names, that is why they're all so messed up.

I'm sorry you had to make all those screenshots, but actually you should take advantage of this section on the config file:
https://github.com/KaiKikuchi/QuickShop/blob/master/src/main/resources/config.yml#L102-L105

And basically set those items name manually on the config.

**Comment by smmmadden** [comment]
Okay, I'll go through the steps of doing that but if this is a known issue wouldn't it be better to provide them already in the file so that server owners don't have to?  This is one of those conditions where as a developer, does it make sense for hundreds of people maybe even thousands, make the exact same changes, or make the change once and provide to everyone?  I'm happy to get them all listed and share it back with you so everyone can benefit from it that works for you?

**Comment by KaiKikuchi** [comment]
> wouldn't it be better to provide them already in the file so that server owners don't have to?

If only they worked on all different minecraft versions... also I really do not have time for naming items so I gave server owners the ability of naming items. It is very useful for localization.

> I'm happy to get them all listed and share it back with you so everyone can benefit from it that works for you?

That may help a lot of other server owners! Be sure to specify your server version.

**Comment by smmmadden** [comment]
I just tried adding them but getting invalid custom item name definitions for each one.  I checked the spigot page you provided (thanks) so I think this may be a spigot issue that they are not listed or at least not with proper names. :-)
custom-items-name:
- NETHER_STALK;Nether Wart;Nether Wart
- GRANITE;Granite;Granite
- PGRANITE;PolishedGranite;Polished Granite
- DIORITE;Diorite;Diorite
- PDIORITE;PolishedDiorite;Polished Diorite
- ANDESITE;Andesite;Andesite
- PANDESITE;PolishedAndesite;Polished Andesite
- MCOBBLEWALL;MossCobbleWall;Mossy Cobble Wall
- DOAKSAPLING;DarkOakSapling;Dark Oak Sapling
- ACACIASAPLING;AcaciaSapling;Acacia Sapling
- PSAPLING;SpruceSapling;Spruce Sapling
- ACACIAPLANK;AcaciaPlank;Acacia Plank
- DOAKPLANK;DarkOakPlank;Dark Oak Plank
- SPLANK;SprucePlank;Spruce Plank
- ACACIALOG;AcaciaLog;Acacia Log
- DARKOAKLOG;DarkOakLog;Dark Oak Log
- SPRUCE;SpruceLog;Spruce Log

I'll see what I can get from Spigot for updating 1.11.2 with the correct names for the above.  Will let you know what they say.
