### ISSUE TITLE
line four of sign enhancement

### ISSUE THREAD

**Issue by smmmadden** [KaiKikuchi/QuickShop#125]
Thanks Kai for making the first line the owner of the shop!  This makes the world of difference to the players.  I didn't see in the messages.yml or config.yml a way to change the bottom row so it fits the language correctly. If it isn't there, I think it would be a great enhancement.
![image](https://cloud.githubusercontent.com/assets/10309346/26230498/77c27366-3c17-11e7-933c-74ce1998ad18.png)

USA - currency .01 to .99 is called "cents"  1 cent, 2 cents, etc
USA - currency 1.00 = one dollar
USA - currency 2.00 = two dollars
Since the last row gets cut off, having just the amount should be sufficient without 0. prefix.  So .75 cents would not show a 0 to the left of the decimal, so that can always be dropped.  Pretty sure that's the case in many languages.  If/when you can add the currency type like $ £ € etc to the front, "for" and dollar/dollars wouldn't be needed.  Think of line four as:  $50.00 and .50 cents would be $.50 or .50 cent(s).
Btw, do you have a donate page, patreon account or something I can donate as a thank you? :-)
Thanks - Steve

**Comment by KaiKikuchi** [comment]
You have to fix that in your economy plugin. Check your economy plugin configuration file and/or documentation. There should be somewhere a setting for formatting the currency, so you can change "20.00 dollars" to "$20.00".

Also you can remove "For" from the line on the messages.yml file:
https://github.com/KaiKikuchi/QuickShop/blob/master/src/main/resources/messages.yml#L108

This is my "personal page": http://mc.kaikk.net/
