### ISSUE TITLE
Shop signs not refreshing

### ISSUE THREAD

**Issue by PyvesB** [KaiKikuchi/QuickShop#128]
Hello KaiKikuchi,

I have just downloaded version 0.9.31 and tested it on three different servers (respectively featuring Minecraft versions 1.11.2, 1.12-pre5 and 1.12-pre6). Two of them are running the default plugin configuration. 

Unfortunately it seems as if the shop signs are no longer updated when a player clicks on them. For instance, suppose I create an empty shop selling a specific item. After putting a stack of that item inside, the shop keeps on showing "Selling 0" no matter what. Everything works as expected when reverting back to version 0.9.29.

Am I doing something wrong or was a regression introduced in the latest version?

Thanks in advance,

Pyves

**Comment by KaiKikuchi** [comment]
Hey. Thank you for your report. Perhaps you need to update your [messages.yml](https://github.com/KaiKikuchi/QuickShop/blob/master/src/main/resources/messages.yml) file (backup it first). Try deleting it and restarting the server. Also when clicking the sign, check the server log: some exception may suggest what is causing the issue.

**Comment by PyvesB** [comment]
On the two servers I mentioned which were "running the default plugin configuration", I did delete the entire _QuickShop_ folder and performed a full server restart.

I did not see any stack traces or notice any usual log messages related to QuickShop in the logs.

**Comment by KaiKikuchi** [comment]
Can you attach your server log?

**Comment by PyvesB** [comment]
Here is the startup log of the 1.12-pre6 server, even though I'm not convinced there's anything interesting inside:
https://gist.github.com/PyvesB/e013fa3d5594e705c2c1ed3746a9f1e2

**Comment by KaiKikuchi** [comment]
Thank you for your report. The issue will be fixed shortly.

**Comment by KaiKikuchi** [comment]
Fixed in version 0.9.32

**Comment by PyvesB** [comment]
Awesome, thanks!
