### ISSUE TITLE
Bukkit page development builds link broken

### ISSUE THREAD

**Issue by datatags** [KaiKikuchi/QuickShop#130]
On the dev.bukkit.org page for this plugin, it says:
## Latest Builds
All builds for my plugins can be found at this link: http://kaikk.net/mc/

But when I click on the link, it returns a 404 Not Found.  I would like to download 0.9.33 but don't see a compiled jar anywhere.  Sorry if I missed it.  Thanks!

**Comment by KaiKikuchi** [comment]
[Project home page on Github -> releases](https://github.com/KaiKikuchi/QuickShop/releases)
