### ISSUE TITLE
Could not pass event InventoryCloseEvent to QuickShop v0.9.33

### ISSUE THREAD

**Issue by Eronair** [KaiKikuchi/QuickShop#132]
Currently QuickShop is posting the following error when a user interacts with their shop on PaperSpigot-1.12-b1122.jar (current latest).

09.38.17 CONSOLE: ERROR]: Could not pass event InventoryCloseEvent to QuickShop v0.9.33
09.38.17 CONSOLE: Source) [?:1.8.0_111]
09.38.17 CONSOLE: Source) [?:1.8.0_111]
09.38.17 CONSOLE: Source) [?:1.8.0_111]
09.38.18 CONSOLE: Source) ~[?:?]

The plugin is preforming just fine, other this this error being thrown most of the time.

**Comment by KaiKikuchi** [comment]
Fixed in version 0.9.34
