### ISSUE TITLE
The item does not look

### ISSUE THREAD

**Issue by yunusalbayrak** [KaiKikuchi/QuickShop#133]
My Config File: https://pastebin.com/nQANebmV
Video : https://youtu.be/f_lPiMuvKjQ
My Plugin List:  https://pastebin.com/8FqDJ2Kj
Please Help me

**Comment by KaiKikuchi** [comment]
I guess you probably mean that the item is not shown above the chest.

You just have to read the config.yml file, and you'll find this: https://github.com/KaiKikuchi/QuickShop/blob/master/src/main/resources/config.yml#L79-L80

**Comment by yunusalbayrak** [comment]
Thanks.
