### ISSUE TITLE
Problem with itemstack displayname with special char and mysql

### ISSUE THREAD

**Issue by FlashLight34** [KaiKikuchi/QuickShop#14]
look this:
        in your matches class in util.java line 804

```
if (stack1.getItemMeta().hasDisplayName() || stack2.getItemMeta().hasDisplayName()) {
            if (stack1.getItemMeta().hasDisplayName() && stack2.getItemMeta().hasDisplayName()) {
                if (!stack1.getItemMeta().getDisplayName().equals(stack2.getItemMeta().getDisplayName())) {


plugin.getLogger().info("Teste2 Matches false util.java: "+stack1.getItemMeta().getDisplayName()+" "+stack2.getItemMeta().getDisplayName());
```

with a display-name like **Tête de déguisement**

```
[18:02:28] [Server thread/INFO]: [QuickShop] Teste2 Matches util.java: T��te de d��guisement Tête de déguisement
```

i dont know if is the serialiser or mysql database but we hate this little bug can you help me to find the fix maybe is because its a BLOB tab and that not got utf8 or anything.

**Comment by KaiKikuchi** [comment]
https://github.com/KaiKikuchi/QuickShop/blob/master/src/main/java/org/maxgamer/quickshop/Util/Util.java#L804

I don't see that line anywhere. Be sure to use the latest version.

**Comment by FlashLight34** [comment]
https://github.com/KaiKikuchi/QuickShop/blob/master/src/main/java/org/maxgamer/quickshop/Util/Util.java#L811

**Comment by KaiKikuchi** [comment]
Binary types doesn't have any encoding, so it shouldn't be an issue. Anyway I'll look into it.
Please provide more info about that item. For example, have you changed the item name? For example, using an Anvil.

**Comment by FlashLight34** [comment]
yes changing name of a SKULL item i prepare an example for u

**Comment by FlashLight34** [comment]
give u a skull like this

```
/give URNAME minecraft:skull 1 3 {display:{Name:"Tête de déguisement",Lore:[A échanger avec le villageois]}}
```

create a chest and create a shop with this item
after this reload qs

```
/qs reload
```

look the sign on the chest turn to 0 quantity

**Comment by KaiKikuchi** [comment]
Ok thanks for your report. I'll check it when I got a little of free time!
Have you tried it with file storage instead of mysql?

**Comment by FlashLight34** [comment]
no only mysql

**Comment by FlashLight34** [comment]
we have better performances with mysql no?

**Comment by FlashLight34** [comment]
ok i think i find a solution, change BLOB to LONGTEXT we are able to set to utf8 after this :)

what is you opinion about this :P

**Comment by KaiKikuchi** [comment]
Have you tried this?

**Comment by FlashLight34** [comment]
yes sir :dancer:

**Comment by FlashLight34** [comment]
![capture](https://cloud.githubusercontent.com/assets/9997676/11107839/63d7b72a-88af-11e5-9b11-3e6ff41eb532.PNG)

**Comment by KaiKikuchi** [comment]
Latest version of QuickShop is not using any BLOB field.
Probably you were using a very old version of QuickShop, then you updated it to this version.
