### ISSUE TITLE
spigot-1.12环境下，部分内容无法显示……

### ISSUE THREAD

**Issue by ghost** [KaiKikuchi/QuickShop#147]
如图：
![o_ cu_k2y7tz2 o1024ey4j](https://user-images.githubusercontent.com/22115175/28492162-46f30aec-6f30-11e7-8b0c-d91301fc3126.png)
![m 20e 24o eav3y3kg vqyw](https://user-images.githubusercontent.com/22115175/28492165-5eeb43da-6f30-11e7-90f7-f534f8770509.png)

**Comment by KaiKikuchi** [comment]
I cannot speak Chinese.

**Comment by ghost** [comment]
Sorry for my poor english.
I think I submitted the BUG to the wrong place,In this pages:
https://coding.net/u/502647092/p/QuickShop/git/
The link to this page points here.
Sorry.Can you remove this issue?
