### ISSUE TITLE
Why does this project depend on CB?

### ISSUE THREAD

**Issue by RoboMWM** [KaiKikuchi/QuickShop#148]
No longer easy for me to compile this myself :c 

Time to download these and Herochat as well :/

Oh, turns out there's more required than just present in the pom.xml... Oh well.

**Comment by KaiKikuchi** [comment]
Hello. As you may not know, I am not the original developer of QuickShop.

I did not make the decision of including dependencies that require downloading them and including them on the build path manually.

Unfortunately, those are currently required for few features of this plugin as Bukkit does not provide any way to do it.

https://github.com/KaiKikuchi/QuickShop/blob/master/src/main/java/org/maxgamer/quickshop/Util/NMS.java

Although it's slightly annoying, I am sure you can download all the required jars that include NMS code (craftbukkit, but also spigot and similar work), and also Herochat, and include that on the project build path.

For the missing entries on the pom.xml... I just added the first jars, then forgot to add the latest. I updated the pom.xml.

**Comment by RoboMWM** [comment]
Ah ok. Not sure what the NMS is used for (haven't looked much into this project, trying to find a replacement for showcasestandalone if it's out there). Thanks.

**Comment by KaiKikuchi** [comment]
It's mainly used to create an ItemStack with 0 as amount so it can be used for the display item (an Item entity above the chest that shows what the chest contains).

Although reflection could be used... I'm too busy for that.

**Comment by RoboMWM** [comment]
Oh... I thought setting item amount to 0 in mc1.11 and later doesn't work... https://github.com/kellerkindt/ShowCaseStandalone/commit/d4be1474cdac081771f13554484abcc3b4db287a

Unless of course that's why you're using NMS.
