### ISSUE TITLE
Potion duplication glitch

### ISSUE THREAD

**Issue by bradyrenting** [KaiKikuchi/QuickShop#154]
Duplication glitch, this video will explain everything.
https://www.youtube.com/watch?v=IS_5fHBnA_E

Item IDs:
    - 373:17472    
    - 373:20288

Version: PaperSpigot 1.8.8
QuickShop Version: 0.9.35
Error log: https://pastebin.com/pZ7Z9HQK

Edit: Config was incomplete.

**Comment by KaiKikuchi** [comment]
You should also post server version, plugin version, and server logs showing the errors when clicking the chest with the potion.

**Comment by iBradyy** [comment]
Version: PaperSpigot 1.8.8
QuickShop Version: 0.9.35
Error log: https://pastebin.com/pZ7Z9HQK

**Comment by KaiKikuchi** [comment]
Your config file is incomplete. You're missing this part of the config: https://github.com/KaiKikuchi/QuickShop/blob/master/src/main/resources/config.yml#L104-L116

Be sure to add it to your config. Please report if that fixes your issue.
