### ISSUE TITLE
 item that does not float

### ISSUE THREAD

**Issue by blackshad00w** [KaiKikuchi/QuickShop#157]
hello I just downloaded QuickShop it works well the only problem know that the item does not float on the chest. I am in version 1.12.2
![2017-11-20_10 58 58](https://user-images.githubusercontent.com/33828823/33012660-e1aff8a0-cde1-11e7-8854-047d30eb2d3e.png)

**Comment by KaiKikuchi** [comment]
https://github.com/KaiKikuchi/QuickShop/blob/master/src/main/resources/config.yml#L79-L80
