### ISSUE TITLE
Offline player can't make money.

### ISSUE THREAD

**Issue by haer0248** [KaiKikuchi/QuickShop#163]
My Essential money use **database connection**, save money.
But when player offline, if anyone buy the offline player item, the offline player can't receive money.
Can you fix this problem? Thanks <3

**Comment by KingBohica** [comment]
Hey, just curious, are you using Essentials or EssentialsX? The original Essentials is no longer being supported, and hasn't been for some time. The project was revitalized under the name EssentialsX.

**Comment by haer0248** [comment]
EssentialsX

**Comment by KaiKikuchi** [comment]
I am sorry but this is not something I can fix, as it's about your economy plugin. You should ask your economy plugin's developer to allow giving money to offline players.

**Comment by haer0248** [comment]
But I use EssentialsX economy, just connect database...
