### ISSUE TITLE
QuickShopWG use???

### ISSUE THREAD

**Issue by Gnurzel** [KaiKikuchi/QuickShop#167]
What do I have to do with the files they work? Please help... thx all

**Comment by KaiKikuchi** [comment]
Use the WorldGuard allow-shop flag to control whether shops are allowed or not in regions.

WorldGuard Flags Documentation: https://worldguard.enginehub.org/en/latest/regions/flags/

**Comment by Gnurzel** [comment]
I understood that with the flag. Where do I have to put the files in? In which folder? Sorry for my bad English.

**Comment by KaiKikuchi** [comment]
Plugins folder
