### ISSUE TITLE
Shops displaying 0 quanity of an item available when chest is nearly full

### ISSUE THREAD

**Issue by froob956** [KaiKikuchi/QuickShop#172]
A little background on where the plugin is being use, to make sure the most useful information is given. It is on a 1.12.2 server, DW 20 to be specific. The toasty networks server if anyone would like to confirm the glitch their selves. (not trying to advertise trying to make sure someone can test it in the same environment as it's happening).

So on to the actual issue, say you open up a single chest shop of wool, and fill all the slots with 64 wool. Someone can buy 1 wool, 27 separate time leaving you with 27 stacks of 63 wool, but a shop that says you are out of the item. 

The other big issue with this being an issue, is for rarer player sold item, (E.G. dragon egg, where the price is always fairly high and volume being sold fairly low). Thus shops "sell out" with multiple pieces still in stock. 

Now my mind, being the way it is, sees this as a way to rule the economy, but I do not believe it is working how it was intended. 

I am no affiliated with toasty networks, in any way (not a mod/admin), just a member trying to help the mod team resolve an issue before they probably even know it is an issue.

**Comment by KaiKikuchi** [comment]
This project is for the Bukkit version of QuickShop, not for the Sponge version.

PS: we know about that issue.
