### ISSUE TITLE
QuickShop Error loading a shop! - Deletes all shops on restart.

### ISSUE THREAD

**Issue by Nesseley** [KaiKikuchi/QuickShop#183]
Hey!

I really want to use your plugin on my server, but everytime i restart the server (I have a automatic restart twice a day) the shops get deleted.

Error: https://pastebin.com/Hj6nKsWK

Spigot: 1.13
QuickShop-1.13-0.0.39-beta
Vault-1.6.7
TheNewEconomy v0.1.1.2

**Comment by Ghost-chu** [comment]
You can use QuickShop-Reremake and trying load database on your server( **First backup** ), and plugin should tell you why this database need deleted, when you fixed it, you can directly switch back to QuickShop

Hope can help you

**Comment by ProsperCraft** [comment]
also, double check file permissions, make sure the server can write to the save location.

**Comment by smmmadden** [comment]
@Nesseley  - Just so you are aware and if it helps:
1. Spigot v1.13 is NOT supported by Spigot.  You should upgrade the server to be using 1.13.1
2. Vault also has been updated for 1.13.1 [Vault ](https://www.spigotmc.org/resources/vault.34315/history).  
3. Check with the developer of [TheNewEconomy ](https://www.spigotmc.org/resources/the-new-economy.7805/) to see if that resource supports the 1.13.1 version or just 1.13 (they are NOT the same) and it only shows support for 1.13, not 1.13.x or 1.13.1.

**Comment by Nesseley** [comment]
I got this fixed in the Re-Remake version of the plugin. 
Theres was something in quickshop erroring on the valuta sign in theneweconomy as far as I understood.
