### ISSUE TITLE
Unlimited Buy Without Money Without op

### ISSUE THREAD

**Issue by wawanboss** [KaiKikuchi/QuickShop#20]
A single player can buy any item in unlimited without this takes away money. I do not own any other shop plugin apart essentials I can not disabled. I also vault but it does not detect QuickShop. When I try / money, it puts me the money of essentials: / Help me please / (sorry for my bad English, i'm french)

**Comment by KaiKikuchi** [comment]
Vault is an Economy API, and Essentials has both an Economy implementation and a Shop implementation. I am not sure why you can't disable Essentials' SignShop. Anyway, it's not related. QuickShop requires Vault and an economy implementation (like Essentials), so everything should just work fine.

Please provide a pastebin of your server log.

**Comment by wawanboss** [comment]
Ok Thanks for your answer. QuickShop doesn't recognize Essentials , the economy implentation. When player buy something in the shop , the money of the player doesn't change. Like if QuickShop doesn't be related with Essentials. Pastebin : http://pastebin.com/TEw8JF3J
Thanks !

**Comment by KaiKikuchi** [comment]
Hello. Essentials hooks to Vault, and QuickShop hooks to Vault just fine (otherwise it would throw an exception). You may want to check QuickShop, Essentials Economy, and Vault configuration files.

**Comment by wawanboss** [comment]
Ok , i'm going to see.

**Comment by wawanboss** [comment]
Ok so it's doesn't work. My essentials economy , QuickShop And Vault Config are there : http://pastebin.com/5cvrb52v

**Comment by KaiKikuchi** [comment]
Are you sure it doesn't work? Because it looks like it should work fine.

I did this test:
1- Created a new shop selling cobblestone for $100
2- Used "/qs setowner [AnotherPlayer]"
3- Checked my balance with /money (it was $2490)
4- Bought 1 cobblestone from the shop
5- Checked my balance again with /money (now it is $2390)

Try this again, please.

**Comment by wawanboss** [comment]
Oh ..... I'M SO SORRY ! I buy some items of my shop :/ So the money is giving to me ! Thanks You Very Much ! And Very Great Plugin !

**Comment by KaiKikuchi** [comment]
Hah don't worry! At least I don't have to fix anything. ;)
