### ISSUE TITLE
Error Log at Server Boot

### ISSUE THREAD

**Issue by ghost** [KaiKikuchi/QuickShop#22]
Hello,

I installed the latest plugin version Quickshop 0.9.10 

Then I got the following error on my console: http://hastebin.com/yaceqakona.vbs

I am running Spigot 1.8.3

**Comment by KaiKikuchi** [comment]
I won't open a vbs file. Probably virus.

**Comment by KaiKikuchi** [comment]
Beside that, you're using an old java version

**Comment by ghost** [comment]
Sorry for the hastebin

Anyway this was posted:

04.12 13:40:09 [Server] INFO ... 6 more
04.12 13:40:09 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[Spigot183.jar:git-Spigot-870264a-0a645a2]
04.12 13:40:09 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[Spigot183.jar:git-Spigot-870264a-0a645a2]
04.12 13:40:09 [Server] INFO at java.lang.Class.forName(Unknown Source) ~[?:1.7.0_72]
04.12 13:40:09 [Server] INFO at java.lang.Class.forName0(Native Method) ~[?:1.7.0_72]
04.12 13:40:09 [Server] INFO at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_72]
04.12 13:40:09 [Server] INFO at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_72]
04.12 13:40:09 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[Spigot183.jar:git-Spigot-870264a-0a645a2]
04.12 13:40:09 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[Spigot183.jar:git-Spigot-870264a-0a645a2]
04.12 13:40:09 [Server] INFO at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.7.0_72]
04.12 13:40:09 [Server] INFO at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_72]
04.12 13:40:09 [Server] INFO at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.7.0_72]
04.12 13:40:09 [Server] INFO at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.7.0_72]
04.12 13:40:09 [Server] INFO at java.net.URLClassLoader.access$100(Unknown Source) ~[?:1.7.0_72]
04.12 13:40:09 [Server] INFO at java.net.URLClassLoader.defineClass(Unknown Source) ~[?:1.7.0_72]
04.12 13:40:09 [Server] INFO at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.7.0_72]
04.12 13:40:09 [Server] INFO at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.7.0_72]
04.12 13:40:09 [Server] INFO at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0_72]
04.12 13:40:09 [Server] INFO Caused by: java.lang.UnsupportedClassVersionError: org/maxgamer/quickshop/QuickShop : Unsupported major.minor version 52.0
04.12 13:40:09 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.7.0_72]
04.12 13:40:09 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:522) [Spigot183.jar:git-Spigot-870264a-0a645a2]
04.12 13:40:09 [Server] INFO at net.minecraft.server.v1_8_R2.DedicatedServer.init(DedicatedServer.java:199) [Spigot183.jar:git-Spigot-870264a-0a645a2]
04.12 13:40:09 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.CraftServer.loadPlugins(CraftServer.java:291) [Spigot183.jar:git-Spigot-870264a-0a645a2]
04.12 13:40:09 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [Spigot183.jar:git-Spigot-870264a-0a645a2]
04.12 13:40:09 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[Spigot183.jar:git-Spigot-870264a-0a645a2]
04.12 13:40:09 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[Spigot183.jar:git-Spigot-870264a-0a645a2]
04.12 13:40:09 [Server] INFO org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: org/maxgamer/quickshop/QuickShop : Unsupported major.minor version 52.0
04.12 13:40:09 [Server] ERROR Could not load 'plugins/QuickShop-0.9.10.jar' in folder 'plugins'

Do I need to tell MC PRO HOSTING to upgrade my JAVA in my SERVER?

**Comment by ghost** [comment]
![image](https://cloud.githubusercontent.com/assets/12205893/11602355/9669b7c0-9b14-11e5-90d6-d0d7f8f03b3a.png)

**Comment by KaiKikuchi** [comment]
Yes, you do. Java 1.8 is required. Older versions are not supported.
