### ISSUE TITLE
Kcauldron easy dupe ways

### ISSUE THREAD

**Issue by EverNife** [KaiKikuchi/QuickShop#24]
Hello there, I want to report an easy way to dupe itens while using this plugin in servers with mods.

If you use a funil to push the itens (lots os mods have itens that do this, blocks that grab droped itens from the floor) for exemple, the funil of OpenBlcoks will dupe the item.

Take a look
![image](https://cloud.githubusercontent.com/assets/11357801/11916438/0ed556b0-a6be-11e5-9e50-7352857dbc64.png)

This is how the itens turn to be called:

![image](https://cloud.githubusercontent.com/assets/11357801/11916449/83fe1530-a6be-11e5-8a3a-124ae3654eff.png)

You can still use the item for crafting other materials.

**Comment by KaiKikuchi** [comment]
Known issue. Disable this: https://github.com/KaiKikuchi/QuickShop/blob/master/src/main/resources/config.yml#L71

**Comment by KaiKikuchi** [comment]
https://github.com/KaiKikuchi/QuickShop/issues/21

**Comment by EverNife** [comment]
oh.. sorry :V

**Comment by KaiKikuchi** [comment]
This bug is hopefully fixed on v0.9.20

**Comment by EverNife** [comment]
Hmm great, i will test it, ty :D
