### ISSUE TITLE
Tax permission

### ISSUE THREAD

**Issue by EverNife** [KaiKikuchi/QuickShop#27]
Is there a permission for players to do not play Taxes?

For exemple, i want my vip-players to do not have to pay taxes, a permission should fit well.

**Comment by KaiKikuchi** [comment]
It'll be added.

**Comment by DarkBlade177** [comment]
How soon :D ?

**Comment by KaiKikuchi** [comment]
No ETA

**Comment by KaiKikuchi** [comment]
Added in version 0.9.17

**Comment by EverNife** [comment]
ty
