### ISSUE TITLE
No item showing

### ISSUE THREAD

**Issue by yetshadow** [KaiKikuchi/QuickShop#28]
I don't know why but my items does not show, when I do qs reload, they show up and disapear.

I'm running spigot 1.8.8 with java 8

**Comment by KaiKikuchi** [comment]
Well, if you mean the items floating above the chests, if you have a public server I'll suggest you to keep that disabled because those items can be duped.

Check this for more info about the dupe: https://github.com/KaiKikuchi/QuickShop/issues/21

**Comment by yetshadow** [comment]
Yeah but, I like those, my server was running verry well in 1.6.4 with this plugin, but, I discovered why it does not work. I'ts incompatible with forge. I've tested without forge and it does not disapear.

**Comment by yetshadow** [comment]
The pluggin work verry well on my server right now but, forge dont let those item appear

**Comment by KaiKikuchi** [comment]
It works on kcauldron. I've tested it on kcauldron. Check the bukkit page... i made a screenshot on a shop selling a SPAMR Launcher from Minefactory Reloaded. Also someone else reported a dupe bug on kcauldron about the floating items.

Anyway I don't support that thing and I'll probably remove it at some point.
