### ISSUE TITLE
Wont recognize money in chat

### ISSUE THREAD

**Issue by johngoo12** [KaiKikuchi/QuickShop#3]
The shop creation will ask for a money value in chat, but when i put one in chat it wont notice it.

latest log to large for pastebin for a non pro user sorry "http://www.megafileupload.com/4Vza/latest.log"

**Comment by KaiKikuchi** [comment]
You're using Herochat. I bet it's causing the issue.

**Comment by KaiKikuchi** [comment]
Can you provide more info about your server version/modpack?
Like Cauldron/KCauldron version, running mods/modpack, etc.

**Comment by johngoo12** [comment]
Kcauldron-1.7.10-1448.133
and Modpack is Direwolf20 1.7.10 1.7.0

**Comment by johngoo12** [comment]
Any fix for this without having to change the chat plugin ?

**Comment by KaiKikuchi** [comment]
I'm sorry for the late reply. This will take a little more time.

**Comment by punkk** [comment]
Hello

In HeroChatlistener.java (line 25) I changed 
if (!plugin.getShopManager().getActions().containsKey(e.getSender().getName()))

to

if (!plugin.getShopManager().getActions().containsKey(e.getSender().getPlayer().getUniqueId()))

and it seems to work fine with HeroChat now. It recognizes money in chat messages and creates shops as it should.

I'm pretty novice in plugin development, so what do you think? Is this enough to fix it or will there be more problems later, if this solutions is used?

**Comment by KaiKikuchi** [comment]
Hello. I'm sorry it took so long but I'm out of town and I don't have time to take care about it.
Are you able to fork this repository, apply your fix, then ask for a pull request, please? If you can't do it, don't worry. I'll apply your patch this week anyway. Thank you for your contribution!

**Comment by punkk** [comment]
Looks like I was too slow with the forking. Glad you had time to apply the patch.

Again, thanks for taking care of this awesome plugin!

**Comment by KaiKikuchi** [comment]
Thank you for your contribution ;)
