### ISSUE TITLE
Plots feature

### ISSUE THREAD

**Issue by ghost** [KaiKikuchi/QuickShop#31]
Hello, your plugin is awesome.
Please could you add plot squared support? Because I gave the permission node plots.admin.interact.other to allow them to buy things from other people plots but some bad players are creating shops touching other players chests in other plots so the owner of the plot can't remove the shops.
Thanks for the support!

**Comment by KaiKikuchi** [comment]
I suggest you to use WorldGuard and AreaShop. That'll be enough for now.

Plots support will be added at some point.

**Comment by ghost** [comment]
Thanks, I'm already using worldguard.
So I hope you'll update your pluing adding the Plot Squared support as soon as possible.
