### ISSUE TITLE
Item check missing

### ISSUE THREAD

**Issue by ghost** [KaiKikuchi/QuickShop#33]
Hello,
players can use shops like locked chests!
I think you need to add a check: if an item in the shop is different from the floating item on the chest, players can't put it in the chest.
Thanks :)
And if you want, please add a item maximum price, thanks.

**Comment by KaiKikuchi** [comment]
I'm sorry but unfortunately that's not possible. Players can still add stuff using a hopper.
I suggest you to make them pay for creating a new shop.

> And if you want, please add a item maximum price, thanks.

This is already included. Check your config file.
