### ISSUE TITLE
Modded chest

### ISSUE THREAD

**Issue by Avaloon** [KaiKikuchi/QuickShop#34]
Hi, i create a chest for my mod and i want to use it with quickshop. It's work for create a shop but quick shop don't read in my chest for buy or sell.
An idea ?

**Comment by KaiKikuchi** [comment]
Well, you're a developer, right?
I don't know anything about your mod etc... but I guess you're not implementing something correctly. Probably, the IInventory interface.

**Comment by Avaloon** [comment]
on my TileEntity i have implements IInventory, minecraft can read my chest with comparator :/

**Comment by KaiKikuchi** [comment]
QuickShop works with several modded chests, like Iron Chest chests
It works with Furnaces, Hoppers, Dispensers, etc...

I suggest you to check Iron Chest source code.

QuickShop uses the Bukkit API InventoryHolder.getInventory(), so it's not using anything "weird".

**Comment by Avaloon** [comment]
thank's i will check the code of Iron chest

**Comment by KaiKikuchi** [comment]
Good luck
