### ISSUE TITLE
QuickShop doesnt work?

### ISSUE THREAD

**Issue by MrAntza** [KaiKikuchi/QuickShop#35]
Hi!

I added QuickShop my server and console says that. I try also many versions but stil:
17.02 15:31:25 [Server] ERROR Error occurred while enabling QuickShop v0.9.8 (Is it up to date?)

Where is the problem?

**Comment by KaiKikuchi** [comment]
You're not providing any useful information about your server or any exception log. Also, you're not using the latest version.

How am I supposed to know where is your problem?

**Comment by MrAntza** [comment]
Im not sure what informtions are useful but i try..

I have these plugins:
And when i install QuickShop it says that when i reload:

Can you help fix this? I really want to use QuickShop :3

17.02 16:07:12 [Plugin Installation] Starting download of QuickShop-0.9.10.jar
17.02 16:07:14 [Plugin Installation] Plugin QuickShop-0.9.10.jar sucesfully installed!

17.02 16:07:26 [Server] INFO Max TNT Explosions: 100
17.02 16:07:26 [Server] INFO Item Despawn Rate: 6000
17.02 16:07:26 [Server] INFO Item Merge Radius: 2.5
17.02 16:07:26 [Server] INFO Arrow Despawn Rate: 1200
17.02 16:07:26 [Server] INFO Allow Zombie Pigmen to spawn from portal blocks: true
17.02 16:07:26 [Server] INFO View Distance: 10
17.02 16:07:26 [Server] INFO Zombie Aggressive Towards Villager: true
17.02 16:07:26 [Server] INFO Chunks to Grow per Tick: 650
17.02 16:07:26 [Server] INFO Clear tick list: false
17.02 16:07:26 [Server] INFO Experience Merge Radius: 3.0
17.02 16:07:26 [Server] INFO -------- World Settings For [Survival_the_end] --------
17.02 16:07:26 [Server] INFO Anti X-Ray: true
17.02 16:07:26 [Server] INFO Engine Mode: 1
17.02 16:07:26 [Server] INFO Hidden Blocks: [14, 15, 16, 21, 48, 49, 54, 56, 73, 74, 82, 129, 130]
17.02 16:07:26 [Server] INFO Replace Blocks: [1, 5]
17.02 16:07:26 [Server] INFO Nerfing mobs spawned from spawners: false
17.02 16:07:26 [Server] INFO Cactus Growth Modifier: 100%
17.02 16:07:26 [Server] INFO Cane Growth Modifier: 100%
17.02 16:07:26 [Server] INFO Melon Growth Modifier: 100%
17.02 16:07:26 [Server] INFO Mushroom Growth Modifier: 100%
17.02 16:07:26 [Server] INFO Pumpkin Growth Modifier: 100%
17.02 16:07:26 [Server] INFO Sapling Growth Modifier: 100%
17.02 16:07:26 [Server] INFO Wheat Growth Modifier: 100%
17.02 16:07:26 [Server] INFO Entity Activation Range: An 32 / Mo 32 / Mi 16
17.02 16:07:26 [Server] INFO Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
17.02 16:07:26 [Server] INFO Mob Spawn Range: 4
17.02 16:07:26 [Server] INFO Alternative Hopper Ticking: false
17.02 16:07:26 [Server] INFO Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
17.02 16:07:26 [Server] INFO Random Lighting Updates: false
17.02 16:07:26 [Server] INFO Structure Info Saving: true
17.02 16:07:26 [Server] INFO Sending up to 10 chunks per packet
17.02 16:07:26 [Server] INFO Max Entity Collisions: 8
17.02 16:07:26 [Server] INFO Custom Map Seeds:  Village: 10387312 Feature: 14357617
17.02 16:07:26 [Server] INFO Max TNT Explosions: 100
17.02 16:07:26 [Server] INFO Item Despawn Rate: 6000
17.02 16:07:26 [Server] INFO Item Merge Radius: 2.5
17.02 16:07:26 [Server] INFO Arrow Despawn Rate: 1200
17.02 16:07:26 [Server] INFO Allow Zombie Pigmen to spawn from portal blocks: true
17.02 16:07:26 [Server] INFO View Distance: 10
17.02 16:07:26 [Server] INFO Zombie Aggressive Towards Villager: true
17.02 16:07:26 [Server] INFO Chunks to Grow per Tick: 650
17.02 16:07:26 [Server] INFO Clear tick list: false
17.02 16:07:26 [Server] INFO Experience Merge Radius: 3.0
17.02 16:07:26 [Server] INFO -------- World Settings For [MiniGames] --------
17.02 16:07:26 [Server] INFO Anti X-Ray: true
17.02 16:07:26 [Server] INFO Engine Mode: 1
17.02 16:07:26 [Server] INFO Hidden Blocks: [14, 15, 16, 21, 48, 49, 54, 56, 73, 74, 82, 129, 130]
17.02 16:07:26 [Server] INFO Replace Blocks: [1, 5]
17.02 16:07:26 [Server] INFO Nerfing mobs spawned from spawners: false
17.02 16:07:26 [Server] INFO Cactus Growth Modifier: 100%
17.02 16:07:26 [Server] INFO Cane Growth Modifier: 100%
17.02 16:07:26 [Server] INFO Melon Growth Modifier: 100%
17.02 16:07:26 [Server] INFO Mushroom Growth Modifier: 100%
17.02 16:07:26 [Server] INFO Pumpkin Growth Modifier: 100%
17.02 16:07:26 [Server] INFO Sapling Growth Modifier: 100%
17.02 16:07:26 [Server] INFO Wheat Growth Modifier: 100%
17.02 16:07:26 [Server] INFO Entity Activation Range: An 32 / Mo 32 / Mi 16
17.02 16:07:26 [Server] INFO Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
17.02 16:07:26 [Server] INFO Mob Spawn Range: 4
17.02 16:07:26 [Server] INFO Alternative Hopper Ticking: false
17.02 16:07:26 [Server] INFO Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
17.02 16:07:26 [Server] INFO Random Lighting Updates: false
17.02 16:07:26 [Server] INFO Structure Info Saving: true
17.02 16:07:26 [Server] INFO Sending up to 10 chunks per packet
17.02 16:07:26 [Server] INFO Max Entity Collisions: 8
17.02 16:07:26 [Server] INFO Custom Map Seeds:  Village: 10387312 Feature: 14357617
17.02 16:07:26 [Server] INFO Max TNT Explosions: 100
17.02 16:07:26 [Server] INFO Item Despawn Rate: 6000
17.02 16:07:26 [Server] INFO Item Merge Radius: 2.5
17.02 16:07:26 [Server] INFO Arrow Despawn Rate: 1200
17.02 16:07:26 [Server] INFO Allow Zombie Pigmen to spawn from portal blocks: true
17.02 16:07:26 [Server] INFO View Distance: 10
17.02 16:07:26 [Server] INFO Zombie Aggressive Towards Villager: true
17.02 16:07:26 [Server] INFO Chunks to Grow per Tick: 650
17.02 16:07:26 [Server] INFO Clear tick list: false
17.02 16:07:26 [Server] INFO Experience Merge Radius: 3.0
17.02 16:07:26 [Server] INFO Disabling LWC-Economy v4.5.0-SNAPSHOT
17.02 16:07:26 [Server] INFO Disabling EssentialsProtect vTeamCity
17.02 16:07:26 [Server] INFO Disabling WorldGuard v6.1
17.02 16:07:26 [Server] INFO Shutting down executor and waiting for any pending tasks...
17.02 16:07:26 [Server] INFO Disabling EssentialsSpawn vTeamCity
17.02 16:07:26 [Server] INFO Disabling HolographicDisplays v2.1.10
17.02 16:07:26 [Server] INFO Disabling LWC v4.5.0-SNAPSHOT
17.02 16:07:26 [Server] INFO Flushing protection updates (0)
17.02 16:07:26 [Server] INFO Disabling EssentialsAntiBuild vTeamCity
17.02 16:07:26 [Server] INFO Disabling EssentialsChat vTeamCity
17.02 16:07:26 [Server] INFO Disabling GroupManager v2.1.31 (Phoenix)
17.02 16:07:26 [Server] INFO WEPIF: GroupManager detected! Using GroupManager for permissions.
17.02 16:07:26 [Server] INFO GroupManager - INFO - Scheduled Data Saving is disabled!
17.02 16:07:26 [Server] INFO GroupManager version 2.1.31 (Phoenix) is disabled!
17.02 16:07:26 [Server] INFO Disabling Essentials vTeamCity
17.02 16:07:26 [Server] INFO Essentials: Using config file enhanced permissions.
17.02 16:07:26 [Server] INFO Permissions listed in as player-commands will be given to all users.
17.02 16:07:26 [Server] INFO Disabling WorldEdit v6.1;no_git_id
17.02 16:07:26 [Server] INFO Disabling MultiWorld v5.2.6
17.02 16:07:26 [Server] INFO Disabled.
17.02 16:07:26 [Server] INFO Disabling CoreProtect v2.11.3
17.02 16:07:26 [Server] INFO Loading CoreProtect v2.11.3
17.02 16:07:26 [Server] INFO Loading MultiWorld v5.2.6
17.02 16:07:26 [Server] INFO Loading WorldEdit v6.1;no_git_id
17.02 16:07:26 [Server] INFO Loading Essentials vTeamCity
17.02 16:07:26 [Server] INFO Loading GroupManager v2.1.31 (Phoenix)
17.02 16:07:26 [Server] INFO Loading EssentialsChat vTeamCity
17.02 16:07:26 [Server] INFO Loading EssentialsAntiBuild vTeamCity
17.02 16:07:26 [Server] INFO Loading LWC v4.5.0-SNAPSHOT
17.02 16:07:26 [Server] INFO Loading HolographicDisplays v2.1.10
17.02 16:07:26 [Server] INFO Loading QuickShop v0.9.10
17.02 16:07:26 [Server] INFO Loading EssentialsSpawn vTeamCity
17.02 16:07:26 [Server] INFO Loading WorldGuard v6.1
17.02 16:07:26 [Server] INFO Loading EssentialsProtect vTeamCity
17.02 16:07:26 [Server] INFO Loading LWC-Economy v4.5.0-SNAPSHOT
17.02 16:07:26 [Server] INFO Enabling LWC v4.5.0-SNAPSHOT
17.02 16:07:26 [Server] INFO Connecting to SQLite
17.02 16:07:26 [Server] INFO Enabling CoreProtect v2.11.3
17.02 16:07:26 [Server] INFO CoreProtect version 2.11.3 is enabled!
17.02 16:07:26 [Server] INFO Using SQLite for data storage.
17.02 16:07:26 [Server] INFO Enabling MultiWorld v5.2.6
17.02 16:07:26 [Server] INFO v5.2.6 enabled.
17.02 16:07:26 [Server] INFO Enabling WorldEdit v6.1;no_git_id
17.02 16:07:27 [Server] INFO WEPIF: Using the Bukkit Permissions API.
17.02 16:07:27 [Server] INFO Using com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_8_R1 as the Bukkit adapter
17.02 16:07:27 [Server] INFO Enabling Essentials vTeamCity
17.02 16:07:27 [Server] INFO Bukkit version format changed. Version not checked.
17.02 16:07:27 [Server] INFO git-Spigot-aee5007 (MC: 1.8)
17.02 16:07:27 [Server] INFO 1.8-R0.1-SNAPSHOT
17.02 16:07:27 [Server] INFO Using locale en_US
17.02 16:07:27 [Server] INFO Using locale en_US
17.02 16:07:27 [Server] INFO Essentials: Using config file enhanced permissions.
17.02 16:07:27 [Server] INFO Permissions listed in as player-commands will be given to all users.
17.02 16:07:27 [Server] INFO Enabling GroupManager v2.1.31 (Phoenix)
17.02 16:07:27 [Server] INFO GroupManager - INFO - World Found: world
17.02 16:07:27 [Server] INFO GroupManager - INFO - World Found: survival
17.02 16:07:27 [Server] INFO GroupManager - INFO - Superperms support enabled.
17.02 16:07:27 [Server] INFO GroupManager - INFO - Scheduled Data Saving is set for every 10 minutes!
17.02 16:07:27 [Server] INFO GroupManager - INFO - Backups will be retained for 24 hours!
17.02 16:07:27 [Server] INFO GroupManager version 2.1.31 (Phoenix) is enabled!
17.02 16:07:27 [Server] INFO WEPIF: GroupManager detected! Using GroupManager for permissions.
17.02 16:07:27 [Server] INFO Essentials: Using GroupManager based permissions.
17.02 16:07:27 [Server] INFO Enabling EssentialsChat vTeamCity
17.02 16:07:27 [Server] INFO Enabling EssentialsAntiBuild vTeamCity
17.02 16:07:27 [Server] INFO Enabling HolographicDisplays v2.1.10
17.02 16:07:27 [Server] INFO Enabling QuickShop v0.9.10
17.02 16:07:27 [Server] INFO Creating messages.yml
17.02 16:07:27 [Server] ERROR Error occurred while enabling QuickShop v0.9.10 (Is it up to date?)
17.02 16:07:27 [Server] INFO java.lang.NoClassDefFoundError: net/milkbowl/vault/economy/Economy
17.02 16:07:27 [Server] INFO at org.maxgamer.quickshop.Economy.Economy_Vault.setupEconomy(Economy_Vault.java:19) ~[?:?]
17.02 16:07:27 [Server] INFO at org.maxgamer.quickshop.Economy.Economy_Vault.<init>(Economy_Vault.java:15) ~[?:?]
17.02 16:07:27 [Server] INFO at org.maxgamer.quickshop.QuickShop.loadEcon(QuickShop.java:330) ~[?:?]
17.02 16:07:27 [Server] INFO at org.maxgamer.quickshop.QuickShop.onEnable(QuickShop.java:120) ~[?:?]
17.02 16:07:27 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[spigot-1.8.0.jar:git-Spigot-aee5007]
17.02 16:07:27 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:333) [spigot-1.8.0.jar:git-Spigot-aee5007]
17.02 16:07:27 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412) [spigot-1.8.0.jar:git-Spigot-aee5007]
17.02 16:07:27 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:352) [spigot-1.8.0.jar:git-Spigot-aee5007]
17.02 16:07:27 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:313) [spigot-1.8.0.jar:git-Spigot-aee5007]
17.02 16:07:27 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.CraftServer.reload(CraftServer.java:742) [spigot-1.8.0.jar:git-Spigot-aee5007]
17.02 16:07:27 [Server] INFO at org.bukkit.Bukkit.reload(Bukkit.java:301) [spigot-1.8.0.jar:git-Spigot-aee5007]
17.02 16:07:27 [Server] INFO at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:23) [spigot-1.8.0.jar:git-Spigot-aee5007]
17.02 16:07:27 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) [spigot-1.8.0.jar:git-Spigot-aee5007]
17.02 16:07:27 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:643) [spigot-1.8.0.jar:git-Spigot-aee5007]
17.02 16:07:27 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchServerCommand(CraftServer.java:629) [spigot-1.8.0.jar:git-Spigot-aee5007]
17.02 16:07:27 [Server] INFO at net.minecraft.server.v1_8_R1.DedicatedServer.aM(DedicatedServer.java:353) [spigot-1.8.0.jar:git-Spigot-aee5007]
17.02 16:07:27 [Server] INFO at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:317) [spigot-1.8.0.jar:git-Spigot-aee5007]
17.02 16:07:27 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:625) [spigot-1.8.0.jar:git-Spigot-aee5007]
17.02 16:07:27 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:528) [spigot-1.8.0.jar:git-Spigot-aee5007]
17.02 16:07:27 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
17.02 16:07:27 [Server] INFO Caused by: java.lang.ClassNotFoundException: net.milkbowl.vault.economy.Economy
17.02 16:07:27 [Server] INFO at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_66]
17.02 16:07:27 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.8.0.jar:git-Spigot-aee5007]
17.02 16:07:27 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.8.0.jar:git-Spigot-aee5007]
17.02 16:07:27 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_66]
17.02 16:07:27 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_66]
17.02 16:07:27 [Server] INFO ... 20 more
17.02 16:07:27 [Server] INFO Enabling EssentialsSpawn vTeamCity
17.02 16:07:27 [Server] INFO Enabling WorldGuard v6.1
17.02 16:07:27 [Server] INFO (Survival) TNT ignition is PERMITTED.
17.02 16:07:27 [Server] INFO (Survival) Lighters are PERMITTED.
17.02 16:07:27 [Server] INFO (Survival) Lava fire is blocked.
17.02 16:07:27 [Server] INFO (Survival) Fire spread is UNRESTRICTED.
17.02 16:07:27 [Server] INFO Loaded configuration for world 'Survival'
17.02 16:07:27 [Server] INFO (Survival_nether) TNT ignition is PERMITTED.
17.02 16:07:27 [Server] INFO (Survival_nether) Lighters are PERMITTED.
17.02 16:07:27 [Server] INFO (Survival_nether) Lava fire is blocked.
17.02 16:07:27 [Server] INFO (Survival_nether) Fire spread is UNRESTRICTED.
17.02 16:07:27 [Server] INFO Loaded configuration for world 'Survival_nether'
17.02 16:07:27 [Server] INFO (Survival_the_end) TNT ignition is PERMITTED.
17.02 16:07:27 [Server] INFO (Survival_the_end) Lighters are PERMITTED.
17.02 16:07:27 [Server] INFO (Survival_the_end) Lava fire is blocked.
17.02 16:07:27 [Server] INFO (Survival_the_end) Fire spread is UNRESTRICTED.
17.02 16:07:27 [Server] INFO Loaded configuration for world 'Survival_the_end'
17.02 16:07:27 [Server] INFO (MiniGames) TNT ignition is PERMITTED.
17.02 16:07:27 [Server] INFO (MiniGames) Lighters are PERMITTED.
17.02 16:07:27 [Server] INFO (MiniGames) Lava fire is blocked.
17.02 16:07:27 [Server] INFO (MiniGames) Fire spread is UNRESTRICTED.
17.02 16:07:27 [Server] INFO Loaded configuration for world 'MiniGames'
17.02 16:07:27 [Server] INFO Loading region data...
17.02 16:07:27 [Server] INFO Enabling EssentialsProtect vTeamCity
17.02 16:07:27 [Server] INFO Enabling LWC-Economy v4.5.0-SNAPSHOT
17.02 16:07:27 [Server] INFO LWC-Economy: Hooked into LWC!
17.02 16:07:27 [Server] INFO Server permissions file permissions.yml is empty, ignoring it
17.02 16:07:27 [Server] INFO CONSOLE: Reload complete.
17.02 16:07:27 [Server] INFO GroupManager - INFO - Bukkit Permissions Updated!
17.02 16:07:27 [Server] INFO [LWC] The updater ran into a minor issue: http://update.griefcraft.com/lwc/branch/stable/LATEST
17.02 16:07:27 [Server] INFO [LWC] This can probably be ignored.
17.02 16:07:29 [Server] INFO --------------------
17.02 16:07:29 [Server] INFO Version 2.12.0 now available.
17.02 16:07:29 [Server] INFO Download: Type "/co version" in-game.
17.02 16:07:29 [Server] INFO --------------------
17.02 16:07:29 [Server] INFO Unlimited MC Hosting: www.hosthorde.com
17.02 16:07:29 [Server] INFO --------------------

**Comment by KaiKikuchi** [comment]
Vault is required.
