### ISSUE TITLE
Seller keep his Items Spigot 1.9

### ISSUE THREAD

**Issue by JTinic** [KaiKikuchi/QuickShop#38]
When I selling Items to a shop, they get doubled. I keep them and get the money. Shop counts correctly. Tried it with different Items ;)

**Comment by KaiKikuchi** [comment]
Hello. You're not providing any info about your server, so I can't help you.

Also, another guy reported here that it works fine on his server.

**Comment by ORelio** [comment]
Hello,

Seems like it work for us on Spigot `1.9-R0.1-SNAPSHOT` and QuickShop `v0.9.8` : 

![2016-03-09_22 50 20](https://cloud.githubusercontent.com/assets/1128206/13651903/bd42c4ce-e649-11e5-81ed-5a4774d504d7.png)

![2016-03-09_22 50 23](https://cloud.githubusercontent.com/assets/1128206/13651905/c1856f82-e649-11e5-988e-195ed6971673.png)

Sorry for the translation not being in English but as you can see the sold items are removed.

**Comment by KaiKikuchi** [comment]
@ORelio thank you for your contribution!

Probably you're using some bugged economy plugin, so I can't do anything about it because you're still not providing any info about your server.
