### ISSUE TITLE
Does this support ADMIN shops?

### ISSUE THREAD

**Issue by Zilacon** [KaiKikuchi/QuickShop#4]
Hey kai, its me the one who nagged you for a 1.6.4 GP+ lol.

Anyways ive hated using SignShop for a very long time, i need to know if i can replace all of my SignShop's Admin Shops with your plugin before i make the change.

Basically a shop to where you can sell or buy infinite quantities of a item from or to a shop that goes into a non existing economy account or specify a economy account for the admin shop name.

Like if i set the config to be infinite items sold or bought to ADMIN-Shop with no economy your plugin will just give players money for items without actually taking it from a account or take economy from a player without actually depositing it into an account.

Or you can setup the account in the config to make a account for ADMIN-Shop then it will make a economy entry for the name ADMIN-Shop and allow people to give that account money and when it runs out people cant sell to it anymore until they buy more stuff.

Something like that.
Anyhoo look forward to your reply. More plugins of yours i got on my servers happier ill be :)

**Comment by KaiKikuchi** [comment]
Hello! I'm a bit confused, but I think you can do it. I suggest you to try it and check the config.yml!
