### ISSUE TITLE
Can't create shops on 1.9

### ISSUE THREAD

**Issue by gerardvanschip** [KaiKikuchi/QuickShop#42]
When I hit the chest with the item I want to sell I'm asked to enter the amount in chat but when I do that I simply see it pop up as chat, no shop is made, no error.

**Comment by KaiKikuchi** [comment]
Hello. This plugin has been reported to be working on bukkit 1.9.

Also, you're not providing any info about your server. Server version? Plugins list? Your server log?

**Comment by gerardvanschip** [comment]
Thanks, my apologies for the lacking info, created a new ticket with the info you requested.
