### ISSUE TITLE
ERROR QuickShop could not hook an economy

### ISSUE THREAD

**Issue by gerardvanschip** [KaiKikuchi/QuickShop#44]
My setup
- Clean server directory
- Spigot 1.9-R0.1-SNAPSHOT (13 versions behind)
- Vault 1.5.6
- Quickshop 0.9.10 and 0.9.12 (Tried both, same results)
- pastebin for the console log is here http://pastebin.com/aBGJiViY

Main error seems to be vault related? Just to be clear, on my spare MC server I wiped the server dir, enabled 1.9, added vault and quickshop, pressed start. Thats it. I googled for this error online but only found articles of people trying to make the old Quickshop talk to another economy system.

Apologies for the previous ticket that was lacking the details you need to troubleshoot. If there is more you need or want me to try let me know.

**Comment by ORelio** [comment]
Do you have an economy plugin on your server? Normally, Vault should load first, then the economy plugin that would hook into Vault, and finally QuickShop that would get the hook from Vault. Vault is only a bridge for allowing economy interactions but it isn't an economy plugin itself.

**Comment by gerardvanschip** [comment]
On the main server I have an economy plugin. I did not load it on the test server as the plugin page said all it needed was Vault. I have fixed it now. Looking at the log file I noticed that most Quickshop errors were database errors. Guess it got corrupted when I moved to 1.9. Luckily there were not that many shops so I have simply trashed the database and am now running with a fresh one.
