### ISSUE TITLE
Can't buy on ADVENTURE MODE

### ISSUE THREAD

**Issue by DevinderFTW** [KaiKikuchi/QuickShop#49]
As Tittle says my would is on ADVENTURE MODE and nobody can't buy/sell nothing on ADVENTURE MODE.
Also I want to edi the First line of the Sign that creates automaticaly... Its says [QuickShop] I want edit that...

**Comment by KaiKikuchi** [comment]
Adventure mode is not supported. The first line of the sign can't be changed.
