### ISSUE TITLE
Muted players cannot use Shops

### ISSUE THREAD

**Issue by DylanDirlam** [KaiKikuchi/QuickShop#5]
Players muted via Essentials are not able to buy/sell from shops- not sure about other mute plugins. Also not sure if this is fixable due to the nature of how mutes and the plugin work.

**Comment by john01dav** [comment]
Just add ignoreCancelled = false to the event handler, ie.

```
@EventHandler(ignoreCancelled = false)
public void asyncPlayerChatEvent(AsyncPlayerChatEvent e){
    //method code here
}
```

**Comment by KaiKikuchi** [comment]
It's not that easy.

**Comment by john01dav** [comment]
You tried it?

**Comment by KaiKikuchi** [comment]
Ya

**Comment by john01dav** [comment]
All right, just trying to help :)
