### ISSUE TITLE
Localized item?

### ISSUE THREAD

**Issue by kunxian888** [KaiKikuchi/QuickShop#51]
Hello, I have been using this plugin for a longtime and loving it. I'm running my online server in Chinese. I already localized the message.yml. However, when I try to open a new shop, it say
[QuickShop]
Chinese
item name in English
Chinese

How can I change the display item name on the sign as well as the click info?

**Comment by KaiKikuchi** [comment]
Added custom items and potions name settings on [config.yml](https://github.com/KaiKikuchi/QuickShop/blob/master/src/main/resources/config.yml#L97) in version 0.9.17.

You can specify all the items in your custom language there.

**Comment by kunxian888** [comment]
Thank you for your continue support, donated

**Comment by kunxian888** [comment]
It seems that if there is something I didn't set for a custom name, it will not let me open a shop with it. Is it possible that if something did not have a custom name, just let it stay as English and open a shop? 
(Since localize all the Potion and enchant effects is pretty hard)

**Comment by KaiKikuchi** [comment]
Hello. Thank you for your contribution!

I tested it already and it works fine. Can you tell me how did you test it and can you provide the server log and eventually some screenshot of the error?

**Comment by KaiKikuchi** [comment]
Nevermind, I found and fixed the error! Download version 0.9.18.

If you find any other issues, please open a new issue! Thanks.

**Comment by kunxian888** [comment]
Thanks, you rock!
