### ISSUE TITLE
OS El Capitian + MC 1.9.2 swapping crouch and sprint (ctrl/shift) breaks

### ISSUE THREAD

**Issue by csmith105** [KaiKikuchi/QuickShop#52]
OS El Capitan + MC 1.9.2, changing the mapping of crouch and sprint, that is mapping crouch to ctrl and sprint to shift, breaks the ability to open the shop dialog in QuickShop on AWNW (the server I play on).

**Comment by KaiKikuchi** [comment]
What is the issue? If your server admin configured the plugin to require sneaking in order to make a shop, you still should be able to create one by holding shift. If this doesn't work, it's not a plugin issue but more a server software issue. Maybe your server has a bad version of spigot.
