### ISSUE TITLE
[Suggestion] Name of the Shop Owner in the Sign

### ISSUE THREAD

**Issue by TKwSni** [KaiKikuchi/QuickShop#53]
I think it should say the name of the owner in the sign on the first Line , its easier to find shops of certain player like that instead of clicking every chest in the area.

if the reason is to show the name of the plugin maybe add it inside the chat message

Thanks

**Comment by KaiKikuchi** [comment]
The reason is not to show the name of the plugin. The reason is the sign must have some kind of ID in order to be recognized faster by the plugin. As your suggestion would affect performances, I will not do it.

**Comment by KaiKikuchi** [comment]
Done in v.0.9.30
