### ISSUE TITLE
Custom item name on sign

### ISSUE THREAD

**Issue by ghost** [KaiKikuchi/QuickShop#56]
Hello :) do you think you could add an option in the config to enable the display of custom items names? Because I have a server with wands and it's confusing when it's shown "stick" or similar on the sign.

Thanks for your amazing work!

**Comment by KaiKikuchi** [comment]
This is already WIP and will come very soon :P

**Comment by ghost** [comment]
Really fast support :D

Thanks! It's a good idea :)

Have a nice day

**Comment by KaiKikuchi** [comment]
Are you using NBT data to make your wands? Can you explain that a little bit? Because Custom item names will be set on config file. Players won't be able to set the name on the sign.

**Comment by ghost** [comment]
I don't think, because I just set the name of the item and unbreakable flag

You could add a check for the name, if it's "Wand" (took from the config list of items) it can be wrote automatically on the sign, so people cannot rename items"poop" or similar to see it on the sign, lol :)

**Comment by KaiKikuchi** [comment]
Added custom items and potions name settings on [config.yml](https://github.com/KaiKikuchi/QuickShop/blob/master/src/main/resources/config.yml#L97) in version 0.9.17.

I hope this fixes your issue! Let me know!
