### ISSUE TITLE
Can't localized sub-item

### ISSUE THREAD

**Issue by kunxian888** [KaiKikuchi/QuickShop#57]
Thank you again for providing the local file. So when I am localizing the item, I found out that I cannot localize sub-item. For example, for No.5 Wood Plank, say I translate it to α, but where there is a shop selling Birch Wood Plank, it will shows up as Wood:2 in English. Same as other item which shares the same id. Like stones, dyes, monster eggs, etc.
![qq 20160531080443](https://cloud.githubusercontent.com/assets/18506411/15659944/78a0b5ee-2706-11e6-8dc2-c35407684159.png)

**Comment by KaiKikuchi** [comment]
You have to use "WOOD*0" for the oak planks. If you do not specify any data value, that name will be used for all the data values.

So this would be a correct example:

```
custom-items-name:
- WOOD*0;OakPlanks;Oak Wood Planks
- WOOD*1;SprucePlanks;Spruce Wood Planks
```

![javaw_2016-05-31_08-47-17](https://cloud.githubusercontent.com/assets/8842403/15665608/6ce85a8a-270c-11e6-8e4d-68a640e66cec.png)

**Comment by kunxian888** [comment]
Oh, its the \* sign, i thought its the : sign
Thank you
