### ISSUE TITLE
Hologram Item Issue

### ISSUE THREAD

**Issue by Renzoez** [KaiKikuchi/QuickShop#58]
Hi, 

Well, Actually i have an error on the Server. I'm running a Spigot 1.9.4 Server  and i can't see the items on the Chests, i mean the Hologram of the Item, and it happend with any chest or any Shop that i created!. Pls i need some Help pls. Thanks :)

**Comment by ghost** [comment]
Are you using forge clientside? It's a known forge bug, try the vanilla client

**Comment by ghost** [comment]
Hi sorry, I did not read that you had an error server-side.

Mh.. are you using Java 8 or Java 7? What's the error? Can you post it?

**Comment by KaiKikuchi** [comment]
When reporting bug, be sure to give all the needed information:
- Plugin version
- Server log (especially the entire exception log)

Anyway, you have to use QS version 0.9.19 for that to work on MC 1.9.4
