### ISSUE TITLE
my users found a dup glitch.

### ISSUE THREAD

**Issue by SliderKP** [KaiKikuchi/QuickShop#60]
DUP GLITCH:
http://puu.sh/pcBf8/1b46309359.jpg

I'm not sure how it works

please fix O.o

**Comment by KaiKikuchi** [comment]
How am I supposed to fix something that I don't know because you can't explain it at all?

**Comment by SliderKP** [comment]
you are right , but I really donot how it works ,

**Comment by KaiKikuchi** [comment]
Before reporting bugs, check if you are using the latest version of the plugin (latest is 0.9.20).

Then provide all info (including server and plugin versions). Explain how they duped and why do you think they duped. Without any of this information, you are just wasting others time.
