### ISSUE TITLE
1.9's Potions are named as "Water" and "LingeringPotion" without their effect

### ISSUE THREAD

**Issue by TNTUP** [KaiKikuchi/QuickShop#61]
Hi, I've updated QuickShop to the latest release on BukkitDev and if I create a Lingering Potion or Potion, it mark as Water for Potions (and it's not supposed to happen, 6 types of potions in the same chest says "Selling 6 Water1 For 2.0 each" (Same for Lingering aswell) and for LingeringPotion it's fine! 

But it doesn't say its effects while we select the shop where it sells the potion

http://i.qcfb.ca/201606020235353.png

http://i.qcfb.ca/201606020290308.png (Inside of the Lingering Potion, it should say its effect and allowing only one effect per shop, older QS in 1.8 allowed only one potion per chest)

http://i.qcfb.ca/201606020265314.png (Inside of the Potions (named as Water) theres 4 types of potions. Is it fixed in the latest dev builds? I've didn't looked up atm.

**Comment by KaiKikuchi** [comment]
Use latest release you can find it here: https://github.com/KaiKikuchi/QuickShop/releases

Also you need to fix your config.yml. This is the default: https://github.com/KaiKikuchi/QuickShop/blob/master/src/main/resources/config.yml

You need to add the custom-items-name and custom-potions-name sections.

**Comment by KaiKikuchi** [comment]
About the lingering potion... it needs to be added I suppose.

**Comment by TNTUP** [comment]
Ahh maybe so, ill give it a try^^ Should I close that issue or keep it open about lingering potions or it should work if I specify customname to it?

**Comment by KaiKikuchi** [comment]
Let's keep it open. Check if using the latest version fixes the issue.

**Comment by TNTUP** [comment]
Sure^^

**Comment by KaiKikuchi** [comment]
I tested it, it doesn't work because they changed a lot of things and it requires some work.

**Comment by TNTUP** [comment]
I tried and it still output "Water 1" and it says Selling 4 although theres 4 types of potions in it, should the chest says the potion effect while clicking on it (like it says the tool enchants)?

**Comment by KaiKikuchi** [comment]
Yes it should. I am working on it give me few hours.

**Comment by KaiKikuchi** [comment]
Please try v.0.9.21 

https://github.com/KaiKikuchi/QuickShop/releases/tag/v.0.9.21
