### ISSUE TITLE
error in console

### ISSUE THREAD

**Issue by SliderKP** [KaiKikuchi/QuickShop#63]
Spigot version 1.8.8
Quickshop 0.9.18

`04.06 10:57:25 [Server] INFO Could not pass event ChunkLoadEvent to QuickShop v0.9.18
04.06 10:57:25 [Server] INFO org.bukkit.event.EventException
04.06 10:57:25 [Server] INFO at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:122) ~[?:?]
04.06 10:57:25 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[overcraft.jar:git-Spigot-db6de12-3f3c65f]
04.06 10:57:25 [Server] INFO at us.Myles.PWP.TransparentListeners.PWPRegisteredListener.callEvent(PWPRegisteredListener.java:30) [PerWorldPlugins.jar:?]
04.06 10:57:25 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [overcraft.jar:git-Spigot-db6de12-3f3c65f]
04.06 10:57:25 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [overcraft.jar:git-Spigot-db6de12-3f3c65f]
04.06 10:57:25 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:59) [overcraft.jar:git-Spigot-db6de12-3f3c65f]
04.06 10:57:25 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:1) [overcraft.jar:git-Spigot-db6de12-3f3c65f]
04.06 10:57:25 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:337) [overcraft.jar:git-Spigot-db6de12-3f3c65f]
04.06 10:57:25 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:295) [overcraft.jar:git-Spigot-db6de12-3f3c65f]
04.06 10:57:25 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:16) [overcraft.jar:git-Spigot-db6de12-3f3c65f]
04.06 10:57:25 [Server] INFO at net.minecraft.server.v1_8_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:115) [overcraft.jar:git-Spigot-db6de12-3f3c65f]
04.06 10:57:25 [Server] INFO at net.minecraft.server.v1_8_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:97) [overcraft.jar:git-Spigot-db6de12-3f3c65f]
04.06 10:57:25 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getChunkAt(CraftWorld.java:126) [overcraft.jar:git-Spigot-db6de12-3f3c65f]
04.06 10:57:25 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getBlockAt(CraftWorld.java:90) [overcraft.jar:git-Spigot-db6de12-3f3c65f]
04.06 10:57:25 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.block.CraftBlock.getRelative(CraftBlock.java:179) [overcraft.jar:git-Spigot-db6de12-3f3c65f]
04.06 10:57:25 [Server] INFO at org.maxgamer.quickshop.Shop.ContainerShop.getSigns(ContainerShop.java:506) [QuickShop-0.9.18.jar:?]
04.06 10:57:25 [Server] INFO at org.maxgamer.quickshop.Shop.ContainerShop.setSignText(ContainerShop.java:486) [QuickShop-0.9.18.jar:?]
04.06 10:57:25 [Server] INFO at org.maxgamer.quickshop.Shop.ContainerShop.setSignText(ContainerShop.java:474) [QuickShop-0.9.18.jar:?]
04.06 10:57:25 [Server] INFO at org.maxgamer.quickshop.Shop.ContainerShop.onLoad(ContainerShop.java:644) [QuickShop-0.9.18.jar:?]
04.06 10:57:25 [Server] INFO at org.maxgamer.quickshop.Listeners.ChunkListener.onChunkLoad(ChunkListener.java:31) [QuickShop-0.9.18.jar:?]
04.06 10:57:25 [Server] INFO at sun.reflect.GeneratedMethodAccessor41.invoke(Unknown Source) ~[?:?]
04.06 10:57:25 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
04.06 10:57:25 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
04.06 10:57:25 [Server] INFO at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:120) [PerWorldPlugins.jar:?]
04.06 10:57:25 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [overcraft.jar:git-Spigot-db6de12-3f3c65f]
04.06 10:57:25 [Server] INFO at us.Myles.PWP.TransparentListeners.PWPRegisteredListener.callEvent(PWPRegisteredListener.java:30) [PerWorldPlugins.jar:?]
04.06 10:57:25 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [overcraft.jar:git-Spigot-db6de12-3f3c65f]
04.06 10:57:25 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [overcraft.jar:git-Spigot-db6de12-3f3c65f]
04.06 10:57:25 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:59) [overcraft.jar:git-Spigot-db6de12-3f3c65f]
04.06 10:57:25 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:1) [overcraft.jar:git-Spigot-db6de12-3f3c65f]
04.06 10:57:25 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:188) [overcraft.jar:git-Spigot-db6de12-3f3c65f]
04.06 10:57:25 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.util.AsynchronousExecutor.finishActive(AsynchronousExecutor.java:347) [overcraft.jar:git-Spigot-db6de12-3f3c65f]
04.06 10:57:25 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:34) [overcraft.jar:git-Spigot-db6de12-3f3c65f]
04.06 10:57:25 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:734) [overcraft.jar:git-Spigot-db6de12-3f3c65f]
04.06 10:57:25 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [overcraft.jar:git-Spigot-db6de12-3f3c65f]
04.06 10:57:25 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [overcraft.jar:git-Spigot-db6de12-3f3c65f]
04.06 10:57:25 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [overcraft.jar:git-Spigot-db6de12-3f3c65f]
04.06 10:57:25 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
04.06 10:57:25 [Server] INFO Caused by: java.lang.NullPointerException: null key in entry: null=7
04.06 10:57:25 [Server] INFO at com.google.common.collect.CollectPreconditions.checkEntryNotNull(CollectPreconditions.java:31) ~[overcraft.jar:git-Spigot-db6de12-3f3c65f]
04.06 10:57:25 [Server] INFO at com.google.common.collect.ImmutableMap.entryOf(ImmutableMap.java:135) ~[overcraft.jar:git-Spigot-db6de12-3f3c65f]
04.06 10:57:25 [Server] INFO at com.google.common.collect.ImmutableMap$Builder.put(ImmutableMap.java:206) ~[overcraft.jar:git-Spigot-db6de12-3f3c65f]
04.06 10:57:25 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.inventory.CraftItemStack.getEnchantments(CraftItemStack.java:299) ~[overcraft.jar:git-Spigot-db6de12-3f3c65f]
04.06 10:57:25 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.inventory.CraftItemStack.getEnchantments(CraftItemStack.java:283) ~[overcraft.jar:git-Spigot-db6de12-3f3c65f]
04.06 10:57:25 [Server] INFO at org.maxgamer.quickshop.Util.Util.matches(Util.java:867) ~[?:?]
04.06 10:57:25 [Server] INFO at org.maxgamer.quickshop.Util.Util.countItems(Util.java:956) ~[?:?]
04.06 10:57:28 [Multicraft] Skipped 9 lines due to rate limit (50/s)`

**Comment by KaiKikuchi** [comment]
1- You are not using the latest version of QuickShop
2- The log is incomplete.

**Comment by SliderKP** [comment]
1- what is the latest version? in bukkit and spigot page is the latest...
2- and this?

`04.06 11:13:15 [Server] ERROR **** THIS IS NOT AN ISSUE TO DO WITH PER WORLD PLUGINS ****
04.06 11:13:15 [Server] INFO Could not pass event ChunkLoadEvent to QuickShop v0.9.18
04.06 11:13:15 [Server] INFO org.bukkit.event.EventException
04.06 11:13:15 [Server] INFO at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:122) ~[?:?]
04.06 11:13:15 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[overcraft.jar:git-Spigot-db6de12-3f3c65f]
04.06 11:13:15 [Server] INFO at us.Myles.PWP.TransparentListeners.PWPRegisteredListener.callEvent(PWPRegisteredListener.java:30) [PerWorldPlugins.jar:?]
04.06 11:13:15 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [overcraft.jar:git-Spigot-db6de12-3f3c65f]
04.06 11:13:15 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [overcraft.jar:git-Spigot-db6de12-3f3c65f]
04.06 11:13:15 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:59) [overcraft.jar:git-Spigot-db6de12-3f3c65f]
04.06 11:13:15 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:1) [overcraft.jar:git-Spigot-db6de12-3f3c65f]
04.06 11:13:15 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:188) [overcraft.jar:git-Spigot-db6de12-3f3c65f]
04.06 11:13:15 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.util.AsynchronousExecutor.finishActive(AsynchronousExecutor.java:347) [overcraft.jar:git-Spigot-db6de12-3f3c65f]
04.06 11:13:15 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:34) [overcraft.jar:git-Spigot-db6de12-3f3c65f]
04.06 11:13:15 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:734) [overcraft.jar:git-Spigot-db6de12-3f3c65f]
04.06 11:13:15 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [overcraft.jar:git-Spigot-db6de12-3f3c65f]
04.06 11:13:15 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [overcraft.jar:git-Spigot-db6de12-3f3c65f]
04.06 11:13:15 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [overcraft.jar:git-Spigot-db6de12-3f3c65f]
04.06 11:13:15 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
04.06 11:13:15 [Server] INFO Caused by: java.lang.NullPointerException: null key in entry: null=6
04.06 11:13:15 [Server] INFO at com.google.common.collect.CollectPreconditions.checkEntryNotNull(CollectPreconditions.java:31) ~[overcraft.jar:git-Spigot-db6de12-3f3c65f]
04.06 11:13:15 [Server] INFO at com.google.common.collect.ImmutableMap.entryOf(ImmutableMap.java:135) ~[overcraft.jar:git-Spigot-db6de12-3f3c65f]
04.06 11:13:15 [Server] INFO at com.google.common.collect.ImmutableMap$Builder.put(ImmutableMap.java:206) ~[overcraft.jar:git-Spigot-db6de12-3f3c65f]
04.06 11:13:15 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.inventory.CraftItemStack.getEnchantments(CraftItemStack.java:299) ~[overcraft.jar:git-Spigot-db6de12-3f3c65f]
04.06 11:13:15 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.inventory.CraftItemStack.getEnchantments(CraftItemStack.java:283) ~[overcraft.jar:git-Spigot-db6de12-3f3c65f]
04.06 11:13:15 [Server] INFO at org.maxgamer.quickshop.Util.Util.matches(Util.java:867) ~[?:?]
04.06 11:13:15 [Server] INFO at org.maxgamer.quickshop.Util.Util.countItems(Util.java:956) ~[?:?]
04.06 11:13:15 [Server] INFO at org.maxgamer.quickshop.Shop.ContainerShop.getRemainingStock(ContainerShop.java:93) ~[?:?]
04.06 11:13:15 [Server] INFO at org.maxgamer.quickshop.Shop.ContainerShop.setSignText(ContainerShop.java:470) ~[?:?]
04.06 11:13:15 [Server] INFO at org.maxgamer.quickshop.Shop.ContainerShop.onLoad(ContainerShop.java:644) ~[?:?]
04.06 11:13:15 [Server] INFO at org.maxgamer.quickshop.Listeners.ChunkListener.onChunkLoad(ChunkListener.java:31) ~[?:?]
04.06 11:13:15 [Server] INFO at sun.reflect.GeneratedMethodAccessor41.invoke(Unknown Source) ~[?:?]
04.06 11:13:15 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
04.06 11:13:15 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
04.06 11:13:15 [Server] INFO at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:120) ~[?:?]`

**Comment by KaiKikuchi** [comment]
https://github.com/KaiKikuchi/QuickShop/releases

From the log, looks like you are using some weird plugin called "PerWorldPlugin" that breaks QuickShop. Avoid using it with QuickShop.

**Comment by SliderKP** [comment]
okey now i charge the latest dev build, hmm i will try with the latest version.

thanks for reply
