### ISSUE TITLE
Double chest shops not working

### ISSUE THREAD

**Issue by kamikazifroasty** [KaiKikuchi/QuickShop#70]
hey there
seems like players can no longer make buy + sell shops using double chests. double chests are only allowing 1 shop even with the quickshop.create.double permission. not getting any errors in the console either.

is anyone else having this issue?

**Comment by KaiKikuchi** [comment]
You aren't providing any useful information about your server. You may want to tell us what's your server version, at least.

**Comment by kamikazifroasty** [comment]
sorry my bad, I'm running spigot build 1.9.2 -r0.1 and the most recent version of quickshop.

**Comment by KaiKikuchi** [comment]
Sorry I don't support MC 1.9.2. It should work anyway.
