### ISSUE TITLE
No money is exchanged...

### ISSUE THREAD

**Issue by roracle** [KaiKikuchi/QuickShop#71]
I'm the admin but I also enjoy playing, so I set up an unlimited gold nugget shop (on my server the goal is to trade in useless gold for virtual cash).  When I sell my gold nuggets, I do not get any money.  When I buy gold nuggets, I am not debited any money.  THIS ONLY HAPPENS FOR THE SHOP CREATOR OF THE UNLIMITED SHOP! 

I am using 0.9.18 on Spigot 1.10.2 (most up to date as of writing this)

I use long form for my money, so it's not "$10.20", it's "10 Goldbacks 20 Nugs" and shows accordingly in QS.

I tried out 0.9.21 as well, but it wouldn't let me use it because it threw an "incompatible with this version" error.

The options are set to where the creator of unlimited chests do not benefit from said chest....oh I see where this is going.  Perhaps that's the wrong approach as an admin may want to trade at an unlimited chest?

**Comment by roracle** [comment]
I found if I change it to a different owner, for example "ServerBank" then it works no problem.  I think I found my solution. :)

**Comment by KaiKikuchi** [comment]
Hello. use version 0.9.22. Shop owners don't get charged for their items.
