### ISSUE TITLE
Error Who disconnected Players

### ISSUE THREAD

**Issue by killianp** [KaiKikuchi/QuickShop#72]
Hi,

sometime when a player is in a shop zone, this error appeared and the player get disconnected : 

on client : Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(2 + length(1) exceeds writer Index(2: UnpooledHeapByteBuf(ridx: 28. widx: 28, cap:2

on server : [Netty Epoll Server IO #1/ERROR]: java.util.ConcurrentModificationException

I have no idea how to fix it 

QuickShop 2.3

Git-paper-808 1.10.2 (this error appeared since 1.9)

**Comment by KaiKikuchi** [comment]
Hello. Probably you're talking about another plugin.

There isn't any QuickShop 2.3 version. [Latest Version Here](https://github.com/KaiKikuchi/QuickShop/releases)

Also, you are not providing any info about your server. And you should provide the entire exception log, with the stack trace.
