### ISSUE TITLE
QS/SilkSpawner Incompatibility

### ISSUE THREAD

**Issue by BetaBurnt** [KaiKikuchi/QuickShop#74]
Not sure if it's an issue on QuickShop's end or SilkSpawners' end, but using the latest development versions of both (and latest official releases of both - on the latest Spigot 1.10.2) you currently can't sell spawners correctly like you used to. It registers it as a generic mob spawner only, not as the specific mob spawner that it is (use to tell you which mob spawner it was when you clicked the shop sign)

**Comment by BetaBurnt** [comment]
To clarify - QS is on version 0.9.20 (as 0.9.21 doesn't load on 1.10.2 - http://pastebin.com/YULuvhBj), SilkSpawners is on [Dev build 353](https://ci.dustplanet.de/job/SilkSpawners/) and Spigot 1.10.2 is up to date with their patches as of this morning. Quickshops in general work fine, you can sell the SilkSpawner spawners but it only lists them as a generic spawner, meaning you could stick any spawner in there and stick a sign above saying it's a rarer spawner and the buyer won't have a clue until after they buy it.

It will only sell the kind of spawner you set it up with, but it doesn't show what spawner it is in the shop description: https://gyazo.com/91ed6be7a0bc32c74d79754a1105c487 or on the sign: https://gyazo.com/e59b8d4f2133f68309c66c28cb0ffd7c

**Comment by BetaBurnt** [comment]
Never mind - I'm a dumbass. Realised it's the custom item names in the config! xD

**Comment by KaiKikuchi** [comment]
Hey, I suggest you to use latest version (0.9.22): https://github.com/KaiKikuchi/QuickShop/releases
