### ISSUE TITLE
Better taxes?

### ISSUE THREAD

**Issue by roracle** [KaiKikuchi/QuickShop#75]
Let's say the taxes are set at 8% (or 0.08 in the config).  When buying OR selling, taxes should be taken from both sides.  There should be the price it's selling for, the taxes on the one buying the item, and taxes on the one receiving the money.  ALSO the two taxes (sales and income) could (and should) be different.

Example if tax was set to 0.08:

Buyer pays in total
[price]*1.08=buyerCost

Server Account gets
[buyerCost]-[price]=salesTax
&
[price]-([price]/1.08)=incomeTax

Player receiving the payment gets
[price]-incomeTax=sellerIncome

**Comment by KaiKikuchi** [comment]
Sorry buy this doesn't make any sense. The plugin works like it does in real life. When a player buys something, they see the final price. The seller just get the money without the taxes. I think the tax system doesn't need any change.

**Comment by roracle** [comment]
In real life, we pay a sales tax, but we also pay an income tax that is reflected on payroll.  In a game, the income tax can be reflected immediately.

**Comment by roracle** [comment]
As a matter of fact, businesses usually pay higher taxes than the person buying from the business.

**Comment by KaiKikuchi** [comment]
Sorry but I will not overcomplicate the tax system. If you really need it for your server, you can ask a developer to fork this project and customize it as you wish.

**Comment by roracle** [comment]
You think it's that complicated?  I'm flabbergasted to be honest.  Oh well, I'll see what I can find out from others, thank you.

**Comment by roracle** [comment]
BTW: I do have it downloaded, where would I go, which class or classes would I use to implement these routines?

**Comment by roracle** [comment]
I just realized how you do the tax, as I was testing it out with my other account using a buy or sell shop.  The player sells an item, and the player selling the item (making income) pays a tax on the item with it being treated like a sales tax.  

IE: The person gaining material wealth (the seller) now has an item and doesn't pay a tax on it.  They only traded their money for the item without incurring any tax or fine of any kind.

Also this: 
According to you, "When a player buys something, they see the final price. The seller just get the money without the taxes."  But then this happens...
![image](https://cloud.githubusercontent.com/assets/9681146/17059862/d2752622-4fec-11e6-9e60-df30893fc9d1.png)
