### ISSUE TITLE
Limited Restock

### ISSUE THREAD

**Issue by vovik3** [KaiKikuchi/QuickShop#78]
Could you add in a restock option for the unlimited shop. So that there would be a limit of 3 bows available for sale at the moment, but if someone bought a bow from the shop it would restock in 30 minutes back to 3 bows.

**Comment by KaiKikuchi** [comment]
Hello. Sorry for the late reply. This can be done with an external plugin. I am not sure if there is a restock plugin available already... but it's not hard to make one.

Just do not set the shop as unlimited shop, then set the restock plugin to restock the chest every 30 minutes. (or something like that).
