### ISSUE TITLE
Items blacklist and modded chests support

### ISSUE THREAD

**Issue by twipsta** [KaiKikuchi/QuickShop#8]
First I would like to thank you for such an awesome plugin. Very easy to use and understand for even the newest of players :)

Now on to the issue - When you add items to the blacklist in config.yml and issue the command '/qs reload' the blacklist is not updated. Items previously blacklisted will stay blacklisted but any new items won't be blacklisted until the next server restart. For me this isn't a huge problem as my server restarts every 8 hours.

This is a separate issue and can open a separate ticket if you like, but I've had issues adding mod container blocks (in particular Iron Chests) to the config - this could be related to the issue above (not reloading config properly) or could be just another or many bukkit/forge quirks. I have tried using unlocalised names and tile entity names - but to no avail. Again for me no real biggie just would of been cool to have an obsidian chest shop hehe.
I realise this is a bukkit plugin, so I'm not expecting the container issue to be even looked at tbh :)

Just incase it helps - I'm running a (K)Cauldron server with the Sky Factory modpack:
Cauldron-MCPC-Plus version git-Cauldron-Reloaded-1.7.10-1.1388.1.0 (MC: 1.7.10) (Implementing API version 1.7.10-R0.1-SNAPSHOT)

**Comment by KaiKikuchi** [comment]
Hello, thank you for your report.
If iron chests don't work after I fix the blacklist issue, you have to open a separate issue.

**Comment by KaiKikuchi** [comment]
Hello, are you sure you're not OP while trying to use a blacklisted item?
There's a "quickshop.bypass.[itemid]" permission that it's default for OPs.

**Comment by twipsta** [comment]
Hi just a follow up - I derped hard while adding the chests to the shop-blocks. I was trying to use the name reported by a debug tool, which bukkit didn't seem to understand.

I ended up creating a shop for obsidian chests, grabbed the item name your plugin reports it as in chat, and added that to the config - replacing the space with an underscore. Now I have obsidian chest shops!
For anyone interested the item name ended up being Ironchest_Blockironchest

As for the blacklist issue, I made sure I was deopped and unranked and issued the reload command from console. As I mentioned earlier the previous blacklisted items (in this case bedrock) was still being blacklisted. But once I reloaded the server everything was working as expected with all new items being blocked.

I also did a quick test then to see if shop-blocks was read on a /qs reload and it wasn't.
I haven't tried the new build I just noticed you had uploaded, so will give that a shot now!

A thing of beauty: http://imgur.com/3ygQuR3
All the Iron Chests being used for shops - ignore the barrels, they where just to fill the chests to test make sure the right number of items are being detected, which it is! :)
I have the item display disabled as the Botania Magnetic Ring likes to try and steal it, and hungry chest like to eat it hehe

Also I would like to thank you for replying so fast. I was kinda hoping I could get this ticket updated before you could see it :)

**Comment by twipsta** [comment]
I have just downloaded and tested the new version, and can confirm that both the blacklist and shop-block changes are now taking effect on a /qs reload.

I can't thank you enough. I seriously expected to be shunned for using a Cauldron based server and the ticket ignored. You sir are awesome!

**Comment by KaiKikuchi** [comment]
Thank you for your contribution! ;)
Unfortunately most of bukkit/forge developers ignore any bug report if it's a cauldron server. In my opinion, that's wrong. I think we should take a look at the issue, at least.

If possible, I try to make my plugins/mods compatible with Cauldron. In fact, I always test them on Cauldron.

I hope you'll continue to support my projects!
