### ISSUE TITLE
(Clientside) QuickShop + Forge

### ISSUE THREAD

**Issue by OS-Void** [KaiKikuchi/QuickShop#80]
Hi,

Hopefully you might be able to fix this little issue that has been on QuickShop for years.
The plugin works amazingly and its one of the most used plugin in the server I play in, but as a player that uses mods, Forge is not compatible with Quickshop, or Quickshop with forge? not sure.

Basically the items above chests do not show up at all on clients running any version of Forge, I spammed /qs reload, and I can notice the item shows up for a split of a second and disappears, for some reason Forge does not want to display the item's made from QuickShop.

This has been an issue since like 2013 until now, I usually have to go around /qs find items, or people that make their own markets/shop have to put up Item Frames on walls for Forge users to find items easily.

I believe this was brought up on Forge a long time ago and they basically said "This isn't the bukkit forums. Thread locked.", and the old developer of QuickShop said "Forge is a mod. Not a server. Closing this ticket as it is invalid."

So us, the players that use mods, and 90% need Forge, get screwed over from both sides of the problem.

Would there be any way you could check if there's a fix for it, why Forge may be unrendering/removing the item?

**Comment by KaiKikuchi** [comment]
Honestly I do not know.

I believe it's not a Forge issue.
In fact, [here you can see a screenshot](http://i.imgur.com/TFXmb3i.png) I made on a kCauldron server with few mods. There is a rocket launcher above the chest. I remember that modded stuff were working correctly.

I think it's a mod causing that issue. I do not remember exactly which mod was causing several issues to Bukkit plugins messing with entities (maybe cofh-related?).

Anyway, there isn't anything I can do to fix the issue... and the mod's author will probably say "I do not support cauldron"... basically avoiding the issue. I can't fix others mods. Also I can't fix others brain. :P

**Comment by OS-Void** [comment]
Well, I died stripped my whole mods, leaving only Forge by itself, and also made a quick test server using spigot-1.10-R0.1-SNAPSHOT and not working. But thank you anyways.

**Comment by KaiKikuchi** [comment]
I don't think so: http://i.imgur.com/SL4VUWT.png
This server is running CraftBukkit version git-Spigot-90f61bc-83a9dbd (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)

**Comment by KaiKikuchi** [comment]
Are you aware of this on the config.yml file?

> #Should we place display items on the chests?
> display-items: true

**Comment by OS-Void** [comment]
Yeah, I have multiple profiles on my launcher, the default minecraft, and the liteloader version DO show items above the chests, but the Forge profile (no mods) DO NOT show the items above the chest. I tried messing with the config.yml and nothing. For whatever reason something implemented into Forge just deletes the entity from the client, when I spam the /qs reload command I can see the items show for a split of a second and then its gone, but like i said Liteloader and No mods clients do display them.

**Comment by KaiKikuchi** [comment]
More than "Forge", it's most likely a Cauldron-like server bug (Thermos?).

But as you can see I was actually able to show the items above the chest with QuickShop on a kCauldron 1.7.10 server with MinefactoryReloaded.

Maybe there is something on the cauldron/kcauldron/thermos config..?

**Comment by KaiKikuchi** [comment]
Just tested on the latest Thermos version: http://i.imgur.com/dJw8CG7.png
This server is running Thermos | https://github.com/CyberdyneCC/Thermos | 1.7.10-R0.1-SNAPSHOT | 1.7.10-1614.58 (MC: 1.7.10)

**Comment by OS-Void** [comment]
Not sure :/
I guess ill keep living with the /qs find command

Thanks for looking into it.
