### ISSUE TITLE
QuickShop showed error in-game... how can I solve?

### ISSUE THREAD

**Issue by Kuroyabumozu** [KaiKikuchi/QuickShop#81]
https://ooo.0o0.ooo/2016/09/01/57c8a2ca9e4b4.png
here is my files in plugin folder
[config.yml](http://paste.ubuntu.com/23122043/)
[messages.yml](http://paste.ubuntu.com/23122030/)

**Comment by KaiKikuchi** [comment]
Hello. That means someone managed to dupe items by using items above QuickShop chests. You should check that nobody is cheating in your server. I'll fix the message to actually show the location.

**Comment by KaiKikuchi** [comment]
Please update to version 0.9.24. The location will be shown.

**Comment by Kuroyabumozu** [comment]
![image](https://cloud.githubusercontent.com/assets/20812714/18220697/2e13a31a-71a7-11e6-83a5-1d21c2325c3b.png)

**Comment by Kuroyabumozu** [comment]
![image](https://cloud.githubusercontent.com/assets/20812714/18220735/b4efbce8-71a7-11e6-8238-9628db91715e.png)

**Comment by Kuroyabumozu** [comment]
there is nothing... how come it showed this error?

**Comment by KaiKikuchi** [comment]
Tp to "ASkyBlock" world at -1797 122 1212... you'll find a hopper. Also try with "/qs clean".
