### ISSUE TITLE
Shops not Working with decimals

### ISSUE THREAD

**Issue by TechnoGeek123-321** [KaiKikuchi/QuickShop#82]
Second issue in about a week D: I don't really know what's up with my server, but I have another issue with shop creation. I start to make a shop:
![2016-09-04_08 17 13](https://cloud.githubusercontent.com/assets/9282760/18230938/4dda2c10-7278-11e6-9b98-d2e1e583e129.png)
Then I type the price with a decimal:
![2016-09-04_08 17 20](https://cloud.githubusercontent.com/assets/9282760/18230941/5aa266e2-7278-11e6-82f9-c9c1f50144eb.png)
And the shop ends up looking like this:
![2016-09-04_08 17 23](https://cloud.githubusercontent.com/assets/9282760/18230946/6aa5cc00-7278-11e6-8843-62980ab114d0.png)
My plugins:
![2016-09-04_08 21 04](https://cloud.githubusercontent.com/assets/9282760/18230954/9c1df85c-7278-11e6-8070-911de80a90a0.png)
This time, I assume that this has nothing to do with the chat plugin. I have tried forcing the bukkit chat handler and disabling Herochat, but that didn't do anything.

**Comment by KaiKikuchi** [comment]
Thank you for your report. Fixed in version 0.9.25.
