### ISSUE TITLE
Not a bug but a feature ask :)

### ISSUE THREAD

**Issue by belfedia** [KaiKikuchi/QuickShop#84]
Could add a config flag to forbid decimal price ?
Like i must forbid price like 1.26, 10.15.
My player sell all material between 0 and 1 (never use better price :/ )

**Comment by KaiKikuchi** [comment]
This was already added: https://github.com/KaiKikuchi/QuickShop/blob/master/src/main/resources/config.yml#L15-L16

**Comment by belfedia** [comment]
Thanks, english isn't my native langage and i don't have understand this config part :)
