### ISSUE TITLE
Plugin Not Loading

### ISSUE THREAD

**Issue by WilSwo** [KaiKikuchi/QuickShop#85]
Hi there. I have used this plugin in the past and love it. I just recently started a new server, tried to load the latest version of the plugin, and Minecraft doesn't even know it exists. Its not showing up in plugin list. Nothing shows up in console with title Quickshop on bootup.

**Comment by KaiKikuchi** [comment]
Hello. You are not providing any info about your server.

Maybe you want to post your server log, and tell me what is your server version.

If nothing appears on the server log, you have not copied it correctly on the plugins folder.

**Comment by Gamerexde** [comment]
**Hi "WilSwo"**

You need to update to java 8... I already have this issue but is now solved. If you are in Debian or Ubuntu you can update trought this scripts:

# 

1) echo "deb http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main" | tee /etc/apt/sources.list.d/webupd8team-java.list

2) echo "deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main" | tee -a /etc/apt/sources.list.d/webupd8team-java.list

3) apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys EEA14886

4) apt-get update

5) apt-get install oracle-java8-installer

# 

Or if is Windows, try to upgrade to java 8 in https://java.com/en/

**Gud bie bi gamerehde**
