### ISSUE TITLE
Optional Messages

### ISSUE THREAD

**Issue by Alphexon** [KaiKikuchi/QuickShop#86]
Please make messages optional, where as if you remove one from messages.yml, nothing will display to the player. As it stands, the player receives a message saying, "Invalid message: [message-id]" if you set it to an empty string. If it's removed completely, it defaults to the default message.

**Comment by KaiKikuchi** [comment]
Any reason for this?

**Comment by Alphexon** [comment]
At least in my case, all the shops are made in protected areas. So the warning about using Lockette, LWC, etc. is pointless.
