### ISSUE TITLE
Do not support mod item as shop

### ISSUE THREAD

**Issue by 5igm** [KaiKikuchi/QuickShop#88]
I installed terrafirmacraft mod in my server, and I add its chest into shop-blocks option.
Shop can be created successfully in terrafirmacraft chest, but after I putted goods into it, stocks always show 0 and server told there was nothing sold.
Could you fix that?
![qq 20160929133628](https://cloud.githubusercontent.com/assets/11610914/18942206/c7d3fe8a-8649-11e6-8cec-d22844016099.png)

QuickShop-0.9.26

**Comment by 5igm** [comment]
Excuse me. I just check it. I found actually shop can detect items in mod shop, but it is pretty weird. I have to exit the server first, then the system will tell me the correct stock number and sell me items.

**Comment by KaiKikuchi** [comment]
Sorry this may be something bad caused by the Terrafirmacraft code. Honestly, it's really weird that happens to you. I don't think I can do something about it.
