### ISSUE TITLE
Decimal prices doesnt work with PaperSpigot

### ISSUE THREAD

**Issue by Poslovitch** [KaiKikuchi/QuickShop#89]
I recently switched my server to PaperSpigot (version: git-Paper-819), and now, I can't create a shop with a decimal price (like $0.07). It will turn to an integer ($0.07 will turn to $7.0 ; $0.15 to $15).

However, I noticed that using /qs price to set a decimal price works, but it's annoying to do this everytime a player wants to create a shop...

**Comment by KaiKikuchi** [comment]
You should not use the $ symbol in chat. Please use latest version and just specify the number like "0.07".
