### ISSUE TITLE
Quick shop not working

### ISSUE THREAD

**Issue by zmw1234** [KaiKikuchi/QuickShop#9]
Hello,

I have quick shop installed the most recent version 0.9.7. On my server that is running spigot .1.8.7 the plugin seems to load and everything, however when you go to click the chest with the item you want to sell it just breaks the chest and does not make a shop.

**Comment by KaiKikuchi** [comment]
Check that you're not in creative mode and that you have permissions to create shops.

Also be sure you haven't added QuickShopWG, that's an extension that allows shops on WorldGuard regions only.
