### ISSUE TITLE
Issue with chest shop Deletion

### ISSUE THREAD

**Issue by LindsayStone** [KaiKikuchi/QuickShop#90]
So we ran into one major issue,  We are using prison cells and when you have a shop there and then the cell get's reset it removes the physical chest however the shop is still listed as existing.  So breaking the chest does nothing to delete the shop.  Resetting the cell does nothing to remove the shop and the /qs clean is not an option to run because it wipes out everyone's shops not just the ones in the cell.  Is there a chestshop deletion command or something that will delete the shop if the chest doesn't exist?

**Comment by KaiKikuchi** [comment]
`/qs clean` doesn't remove all the shops, but just the invalid shops (usually shops removed by something that doesn't call the break event). So, it should work fine.

Currently, the only way to manually remove someone's shop chest is by using the QuickShop API. If `/qs clean` doesn't really work for you and you're not a developer, you may want to hire one and make him make a plugin that does exactly what you want by using the QuickShop API. It's easy enough.
