### ISSUE TITLE
1.11 support

### ISSUE THREAD

**Issue by datatags** [KaiKikuchi/QuickShop#91]
I updated my server to 1.11 and QuickShop said it was not compatible with this version.  Is this still being worked on?  Because I put a lot of effort into creating admin shops for almost every item, and I don't want to have to do that again with another plugin.  QuickShop has been a favorite of mine since the start and I don't want to see it go.  Thanks for reading!

Tl;dr:  Doesn't work with 1.11

**Comment by TNTUP** [comment]
Seconding this suggestion! Looking forward from you @KaiKikuchi ^^ :D Also, take your time for it

**Comment by KaiKikuchi** [comment]
Done in version 0.9.27
