### ISSUE TITLE
Double chest shop creation not possible when using click feature

### ISSUE THREAD

**Issue by PyvesB** [KaiKikuchi/QuickShop#96]
Hello,

I believe the issue is similar to the one reported in #70. The following scenario can reproduce the issue:
- place a double chest.
- create a shop in the first chest.
- try to create a new shop in the second chest by clicking on it with the item you want to sell.

Instead of asking you to enter the price of the shop in the chat to create a new shop, QuickShop displays the shop information of the first shop. I believe this bug was introduced by commit 37fb3ec3a7c1b2ebb8ad0f5ed4399650a5c349c4, with the new functionality suggested by #16.

The feature of #16 is very convenient, but should not be enabled if you are the owner of the shop. That way, you could still freely be able to create double chest shops using click functionality.

Cheers,

Pyves

**Comment by KaiKikuchi** [comment]
Hey. Thanks for the report and the PR.

**Comment by PyvesB** [comment]
No problem. ;-)
