### ISSUE TITLE
Players losing connection the server when idling next to shops

### ISSUE THREAD

**Issue by gerardvanschip** [KaiKikuchi/QuickShop#98]
We have noticed since going to MC 1.11 that players get disconnected when idling around Quickshop locations, the more shops the higher the chance of getting the connection dropped.

**Comment by gerardvanschip** [comment]
The error we get is "Internal Exception: io.netty.handler.codec.decoderexception; f: loading NBT data". If I disable the plugin we do not get this error.

**Comment by SpaZMonKeY777** [comment]
Same here as well, but the only error that shows up in console when I get disconnected is this:

```
[11:10:42 ERROR]: java.util.ConcurrentModificationException
[11:10:42 INFO]: SpaZMonKeY777 lost connection: Internal Exception: java.io.IOException: Error while read(...): Connection reset by peer
```

I have tested this in many different ways, leaving an account afk in a no-shop zone, and it never disconnects over 24 hours. And one I leave afk at the same time in a shop area will disconnect very randomly. Sometimes it wont disconnect for an hour, sometimes it will do it 3x within 10 minutes. But quickshops are definitely the only linking cause of this :(

**Comment by KaiKikuchi** [comment]
So are you sure you don't get the issue if you're near a shop but with the plugin disabled?

Also do you have the config option "display item" on?  If so disable it.

**Comment by KaiKikuchi** [comment]
Please try version 0.9.29
