### ISSUE TITLE
Shops taking money, not giving items.

### ISSUE THREAD

**Issue by CobaltSparkz** [KaiKikuchi/QuickShop#99]
Hey there,

After updating my server to 1.11.2 and using QS Version 0.9.28 (From your website repository), I've noticed that you can punch a sign, type in how many items you want, it'll take your money, but not grant the items. 

Pastebin of error spewed out: 

http://pastebin.com/QN68JgzY

If there's anything I'm doing wrong, or can change, please, let me know - I saw some text relating to essentials, but I'm not going to throw out guesses as to what the issue is.

Cheers

Sparkz

**Comment by KaiKikuchi** [comment]
Hello. Is this happening with any shop or just some shop? It could be an issue with your economy plugin.

**Comment by CobaltSparkz** [comment]
It's happening with all shops, that I can see - we are on spigot 1.11.2 and using Essentials X, latest build

Sparkz

**Comment by KaiKikuchi** [comment]
Have you deleted *.dat files from the world/playerdata/ folder? Also try to set "tax" to 0.

**Comment by KaiKikuchi** [comment]
I've checked the QuickShop code, and it's fine. It's probably your economy plugin being faulty.

**Comment by CobaltSparkz** [comment]
Ok, I'll look to see if I can find a better version of essentials X if there is one, then. 

Cheers!
